# Main program: modules/compiler_full.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.section .rodata
.div_zero_msg:
    .string "Division by zero is not allowed!"

.text


# Function: report_error
.global report_error
report_error:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: phase at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: message at -16(%rbp)
    movq %rsi, -16(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_0: .asciz "[ERROR] Compilation error occurred"
    .section .text
    leaq _str_0(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -8(%rbp), %r8  # Load phase
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -16(%rbp), %r8  # Load message
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lreport_error_return

.Lreport_error_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: report_warning
.global report_warning
report_warning:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: phase at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: message at -16(%rbp)
    movq %rsi, -16(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_1: .asciz "[WARNING] Compilation warning"
    .section .text
    leaq _str_1(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -8(%rbp), %r8  # Load phase
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -16(%rbp), %r8  # Load message
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lreport_warning_return

.Lreport_warning_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: tokenize_source
.global tokenize_source
tokenize_source:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: source_code at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_2: .asciz "[LEXER] Starting tokenization..."
    .section .text
    leaq _str_2(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_3: .asciz "  ✓ Tokenization complete (stub)"
    .section .text
    leaq _str_3(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $42, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltokenize_source_return

.Ltokenize_source_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: validate_tokens
.global validate_tokens
validate_tokens:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_4: .asciz "[LEXER] Validating tokens..."
    .section .text
    leaq _str_4(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_5: .asciz "  ✓ Token validation complete"
    .section .text
    leaq _str_5(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lvalidate_tokens_return

.Lvalidate_tokens_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: parse_tokens
.global parse_tokens
parse_tokens:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_6: .asciz "[PARSER] Starting AST construction..."
    .section .text
    leaq _str_6(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_7: .asciz "  ✓ AST construction complete (stub)"
    .section .text
    leaq _str_7(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $15, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_tokens_return

.Lparse_tokens_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: validate_ast
.global validate_ast
validate_ast:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_8: .asciz "[PARSER] Validating AST..."
    .section .text
    leaq _str_8(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_9: .asciz "  ✓ AST validation complete"
    .section .text
    leaq _str_9(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lvalidate_ast_return

.Lvalidate_ast_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: codegen_ast
.global codegen_ast
codegen_ast:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_10: .asciz "[CODEGEN] Starting LLVM IR generation..."
    .section .text
    leaq _str_10(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_11: .asciz "  ✓ LLVM IR generation complete (stub)"
    .section .text
    leaq _str_11(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    .section .rodata
    _str_12: .asciz "define i64 @main() { entry: ret i64 0 }"
    .section .text
    leaq _str_12(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lcodegen_ast_return

.Lcodegen_ast_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: validate_llvm_ir
.global validate_llvm_ir
validate_llvm_ir:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: ir_code at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_13: .asciz "[CODEGEN] Validating LLVM IR..."
    .section .text
    leaq _str_13(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_14: .asciz "  ✓ LLVM IR validation complete"
    .section .text
    leaq _str_14(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lvalidate_llvm_ir_return

.Lvalidate_llvm_ir_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: compile_source
.global compile_source
compile_source:
    pushq %rbp
    movq %rsp, %rbp
    subq $40, %rsp
    # Parameter: source_code at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_15: .asciz "========================================"
    .section .text
    leaq _str_15(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_16: .asciz "  MELP Compiler - Pipeline Starting"
    .section .text
    leaq _str_16(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_17: .asciz "========================================"
    .section .text
    leaq _str_17(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_18: .asciz ""
    .section .text
    leaq _str_18(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_19: .asciz "Phase 1: Lexical Analysis"
    .section .text
    leaq _str_19(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_20: .asciz "----------------------------"
    .section .text
    leaq _str_20(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: token_count at -16(%rbp)
    # Assignment: token_count = ...

    # Arithmetic expression
    # Function call: tokenize_source()
    movq -8(%rbp), %r10  # Load source_code
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call tokenize_source
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to token_count
    # Variable: validation_result at -24(%rbp)
    # Assignment: validation_result = ...

    # Arithmetic expression
    # Function call: validate_tokens()
    call validate_tokens
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to validation_result

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_21: .asciz ""
    .section .text
    leaq _str_21(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_22: .asciz "Phase 2: Parsing"
    .section .text
    leaq _str_22(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_23: .asciz "----------------------------"
    .section .text
    leaq _str_23(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: node_count at -32(%rbp)
    # Assignment: node_count = ...

    # Arithmetic expression
    # Function call: parse_tokens()
    call parse_tokens
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Store to node_count
    # Assignment: validation_result = ...

    # Arithmetic expression
    # Function call: validate_ast()
    call validate_ast
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to validation_result

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_24: .asciz ""
    .section .text
    leaq _str_24(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_25: .asciz "Phase 3: Code Generation"
    .section .text
    leaq _str_25(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_26: .asciz "----------------------------"
    .section .text
    leaq _str_26(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: llvm_ir at -40(%rbp)
    # Assignment: llvm_ir = ...

    # Arithmetic expression
    # Function call: codegen_ast()
    call codegen_ast
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Store to llvm_ir
    # Assignment: validation_result = ...

    # Arithmetic expression
    # Function call: validate_llvm_ir()
    movq -40(%rbp), %r10  # Load llvm_ir
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call validate_llvm_ir
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to validation_result

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_27: .asciz ""
    .section .text
    leaq _str_27(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_28: .asciz "========================================"
    .section .text
    leaq _str_28(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_29: .asciz "Compilation Summary:"
    .section .text
    leaq _str_29(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_30: .asciz "  Status: SUCCESS"
    .section .text
    leaq _str_30(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_31: .asciz "========================================"
    .section .text
    leaq _str_31(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_32: .asciz ""
    .section .text
    leaq _str_32(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -40(%rbp), %r8  # Load llvm_ir
    movq %r8, %rax  # Return value
    jmp .Lcompile_source_return

.Lcompile_source_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: get_version
.global get_version
get_version:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    .section .rodata
    _str_33: .asciz "0.1.0"
    .section .text
    leaq _str_33(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_version_return

.Lget_version_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: get_compiler_name
.global get_compiler_name
get_compiler_name:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    .section .rodata
    _str_34: .asciz "MELP Compiler"
    .section .text
    leaq _str_34(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_compiler_name_return

.Lget_compiler_name_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: get_build_date
.global get_build_date
get_build_date:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    .section .rodata
    _str_35: .asciz "17 Aralik 2025"
    .section .text
    leaq _str_35(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_build_date_return

.Lget_build_date_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: print_usage
.global print_usage
print_usage:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_36: .asciz "Usage: compiler [options] <input.mlp> <output.ll>"
    .section .text
    leaq _str_36(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_37: .asciz ""
    .section .text
    leaq _str_37(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_38: .asciz "Options:"
    .section .text
    leaq _str_38(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_39: .asciz "  -h, --help     Show this help message"
    .section .text
    leaq _str_39(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_40: .asciz "  -v, --version  Show compiler version"
    .section .text
    leaq _str_40(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_41: .asciz ""
    .section .text
    leaq _str_41(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_42: .asciz "Examples:"
    .section .text
    leaq _str_42(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_43: .asciz "  compiler program.mlp output.ll"
    .section .text
    leaq _str_43(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_44: .asciz "  compiler --version"
    .section .text
    leaq _str_44(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lprint_usage_return

.Lprint_usage_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: print_version
.global print_version
print_version:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    # Function call: get_compiler_name()
    call get_compiler_name
    movq %rax, %r8  # Function return value
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_45: .asciz "Version: "
    .section .text
    leaq _str_45(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    # Function call: get_version()
    call get_version
    movq %rax, %r8  # Function return value
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_46: .asciz "Build: "
    .section .text
    leaq _str_46(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    # Function call: get_build_date()
    call get_build_date
    movq %rax, %r8  # Function return value
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lprint_version_return

.Lprint_version_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: read_source_file
.global read_source_file
read_source_file:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: filename at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_47: .asciz "[INFO] Reading file:"
    .section .text
    leaq _str_47(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -8(%rbp), %r8  # Load filename
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_48: .asciz ""
    .section .text
    leaq _str_48(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: content at -16(%rbp)

    # Arithmetic expression
    # Function call: read_file()
    movq -8(%rbp), %r10  # Load filename
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call read_file
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize content
    movq -16(%rbp), %r8  # Load content
    movq %r8, %rax  # Return value
    jmp .Lread_source_file_return

.Lread_source_file_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: write_output_file
.global write_output_file
write_output_file:
    pushq %rbp
    movq %rsp, %rbp
    subq $24, %rsp
    # Parameter: filename at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: content at -16(%rbp)
    movq %rsi, -16(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_49: .asciz "[INFO] Writing file:"
    .section .text
    leaq _str_49(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -8(%rbp), %r8  # Load filename
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_50: .asciz ""
    .section .text
    leaq _str_50(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: result at -24(%rbp)

    # Arithmetic expression
    # Function call: write_file()
    movq -8(%rbp), %r10  # Load filename
    pushq %r10  # Save arg 1
    movq -16(%rbp), %r10  # Load content
    pushq %r10  # Save arg 2
    popq %rsi  # Restore arg 2
    popq %rdi  # Restore arg 1
    call write_file
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Initialize result

    # If statement

    # Comparison with logical chaining
    movq -24(%rbp), %r8  # Load result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_0
    # Then body

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_51: .asciz "  ✓ File written successfully"
    .section .text
    leaq _str_51(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    jmp .if_end_1
.if_else_0:
    # Else body

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_52: .asciz "  ✗ Error writing file"
    .section .text
    leaq _str_52(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_1:
    movq -24(%rbp), %r8  # Load result
    movq %r8, %rax  # Return value
    jmp .Lwrite_output_file_return

.Lwrite_output_file_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: file_exists
.global file_exists
file_exists:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: filename at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lfile_exists_return

.Lfile_exists_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: parse_arguments
.global parse_arguments
parse_arguments:
    pushq %rbp
    movq %rsp, %rbp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_53: .asciz "[INFO] Parsing command-line arguments"
    .section .text
    leaq _str_53(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_54: .asciz "[INFO] Using default: input.mlp -> output.ll"
    .section .text
    leaq _str_54(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_55: .asciz "[MODE] Test Mode - Using default files"
    .section .text
    leaq _str_55(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_56: .asciz ""
    .section .text
    leaq _str_56(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_arguments_return

.Lparse_arguments_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: compile_file
.global compile_file
compile_file:
    pushq %rbp
    movq %rsp, %rbp
    subq $40, %rsp
    # Parameter: input_file at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: output_file at -16(%rbp)
    movq %rsi, -16(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_57: .asciz ""
    .section .text
    leaq _str_57(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_58: .asciz "========================================"
    .section .text
    leaq _str_58(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_59: .asciz "  MELP Compiler - Compilation"
    .section .text
    leaq _str_59(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_60: .asciz "========================================"
    .section .text
    leaq _str_60(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_61: .asciz ""
    .section .text
    leaq _str_61(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_62: .asciz "Input:  "
    .section .text
    leaq _str_62(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -8(%rbp), %r8  # Load input_file
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_63: .asciz ""
    .section .text
    leaq _str_63(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_64: .asciz "Output: "
    .section .text
    leaq _str_64(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    movq -16(%rbp), %r8  # Load output_file
    movq %r8, %rdi
    call sto_print_int64
    movq $10, %rdi  # newline char
    call putchar
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_65: .asciz ""
    .section .text
    leaq _str_65(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_66: .asciz ""
    .section .text
    leaq _str_66(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_67: .asciz "[1/3] Reading source file..."
    .section .text
    leaq _str_67(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: source_code at -24(%rbp)
    # Assignment: source_code = ...

    # Arithmetic expression
    # Function call: read_source_file()
    movq -8(%rbp), %r10  # Load input_file
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call read_source_file
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to source_code

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_68: .asciz "  ✓ Source file read successfully"
    .section .text
    leaq _str_68(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_69: .asciz ""
    .section .text
    leaq _str_69(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_70: .asciz "[2/3] Compiling..."
    .section .text
    leaq _str_70(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: llvm_ir at -32(%rbp)
    # Assignment: llvm_ir = ...

    # Arithmetic expression
    # Function call: compile_source()
    movq -24(%rbp), %r10  # Load source_code
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call compile_source
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Store to llvm_ir

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_71: .asciz "  ✓ Compilation successful"
    .section .text
    leaq _str_71(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_72: .asciz ""
    .section .text
    leaq _str_72(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_73: .asciz "[3/3] Writing output file..."
    .section .text
    leaq _str_73(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: write_result at -40(%rbp)
    # Assignment: write_result = ...

    # Arithmetic expression
    # Function call: write_output_file()
    movq -16(%rbp), %r10  # Load output_file
    pushq %r10  # Save arg 1
    movq -32(%rbp), %r10  # Load llvm_ir
    pushq %r10  # Save arg 2
    popq %rsi  # Restore arg 2
    popq %rdi  # Restore arg 1
    call write_output_file
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Store to write_result

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_74: .asciz "  ✓ Output file written successfully"
    .section .text
    leaq _str_74(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_75: .asciz ""
    .section .text
    leaq _str_75(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_76: .asciz "========================================"
    .section .text
    leaq _str_76(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_77: .asciz "Compilation completed successfully!"
    .section .text
    leaq _str_77(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_78: .asciz "========================================"
    .section .text
    leaq _str_78(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_79: .asciz ""
    .section .text
    leaq _str_79(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lcompile_file_return

.Lcompile_file_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: main
.global main
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_80: .asciz ""
    .section .text
    leaq _str_80(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_81: .asciz "================================================"
    .section .text
    leaq _str_81(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_82: .asciz "  MELP Compiler v0.1.0"
    .section .text
    leaq _str_82(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_83: .asciz "  Stage 1 Self-Hosting Compiler"
    .section .text
    leaq _str_83(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_84: .asciz "  Date: 17 Aralik 2025"
    .section .text
    leaq _str_84(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_85: .asciz "================================================"
    .section .text
    leaq _str_85(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_86: .asciz ""
    .section .text
    leaq _str_86(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: arg_mode at -8(%rbp)
    # Assignment: arg_mode = ...

    # Arithmetic expression
    # Function call: parse_arguments()
    call parse_arguments
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -8(%rbp)  # Store to arg_mode
    # Variable: input_file at -16(%rbp)
    # Variable: output_file at -24(%rbp)
    # Assignment: input_file = ...

    # Arithmetic expression
    .section .rodata
    _str_87: .asciz "input.mlp"
    .section .text
    leaq _str_87(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to input_file
    # Assignment: output_file = ...

    # Arithmetic expression
    .section .rodata
    _str_88: .asciz "output.ll"
    .section .text
    leaq _str_88(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to output_file
    # Variable: result at -32(%rbp)
    # Assignment: result = ...

    # Arithmetic expression
    # Function call: compile_file()
    movq -16(%rbp), %r10  # Load input_file
    pushq %r10  # Save arg 1
    movq -24(%rbp), %r10  # Load output_file
    pushq %r10  # Save arg 2
    popq %rsi  # Restore arg 2
    popq %rdi  # Restore arg 1
    call compile_file
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Store to result

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_89: .asciz ""
    .section .text
    leaq _str_89(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_90: .asciz "================================================"
    .section .text
    leaq _str_90(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_91: .asciz "  Status: SUCCESS"
    .section .text
    leaq _str_91(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_92: .asciz "================================================"
    .section .text
    leaq _str_92(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -32(%rbp), %r8  # Load result
    movq %r8, %rax  # Return value
    jmp .Lmain_return

.Lmain_return:
    movq %rbp, %rsp
    popq %rbp
    ret
