; Generated by MLP 26-Module Compiler
; Source: ../../examples/hello/hello_world.mlp

global _start

section .data
    str_1 db "Merhaba Dünya!", 10
    str_1_len equ $ - str_1
    str_2 db "MLP 26-modül sistemi çalışıyor!", 10
    str_2_len equ $ - str_2
    str_3 db "Hello World from MLP!", 10
    str_3_len equ $ - str_3

section .text
_start:
    ; Print string 1
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_1]
    mov rdx, str_1_len
    syscall

    ; Print string 2
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_2]
    mov rdx, str_2_len
    syscall

    ; Print string 3
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_3]
    mov rdx, str_3_len
    syscall

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
