; Generated by MLP 26-Module Compiler
; Source: ../../examples/hello/test_print.mlp

global _start

section .data
    str_1 db "=== MLP Test Suite ===", 10
    str_1_len equ $ - str_1
    str_2 db "", 10
    str_2_len equ $ - str_2
    str_3 db "Test 1: Türkçe karakterler", 10
    str_3_len equ $ - str_3
    str_4 db "Çalışıyor: ç ğ ı ö ş ü", 10
    str_4_len equ $ - str_4
    str_5 db "", 10
    str_5_len equ $ - str_5
    str_6 db "Test 2: English characters", 10
    str_6_len equ $ - str_6
    str_7 db "Working: ABC xyz 123", 10
    str_7_len equ $ - str_7
    str_8 db "", 10
    str_8_len equ $ - str_8
    str_9 db "Test 3: Special symbols", 10
    str_9_len equ $ - str_9
    str_10 db "Symbols: !@#$%^&*()", 10
    str_10_len equ $ - str_10
    str_11 db "", 10
    str_11_len equ $ - str_11
    str_12 db "=== All Tests Passed! ===", 10
    str_12_len equ $ - str_12

section .text
_start:
    ; Print string 1
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_1]
    mov rdx, str_1_len
    syscall

    ; Print string 2
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_2]
    mov rdx, str_2_len
    syscall

    ; Print string 3
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_3]
    mov rdx, str_3_len
    syscall

    ; Print string 4
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_4]
    mov rdx, str_4_len
    syscall

    ; Print string 5
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_5]
    mov rdx, str_5_len
    syscall

    ; Print string 6
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_6]
    mov rdx, str_6_len
    syscall

    ; Print string 7
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_7]
    mov rdx, str_7_len
    syscall

    ; Print string 8
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_8]
    mov rdx, str_8_len
    syscall

    ; Print string 9
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_9]
    mov rdx, str_9_len
    syscall

    ; Print string 10
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_10]
    mov rdx, str_10_len
    syscall

    ; Print string 11
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_11]
    mov rdx, str_11_len
    syscall

    ; Print string 12
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_12]
    mov rdx, str_12_len
    syscall

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
