# Generated by MELP Simple Codegen
.text

# Function: generate_print_syscall
.globl generate_print_syscall
.type generate_print_syscall, @function
generate_print_syscall:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_print_syscall
.size generate_print_syscall, .-generate_print_syscall

# Function: compile_one_print
.globl compile_one_print
.type compile_one_print, @function
compile_one_print:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call generate_print_syscall
    # Unknown variable: code
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_one_print
.size compile_one_print, .-compile_one_print

# Function: compile_three_prints
.globl compile_three_prints
.type compile_three_prints, @function
compile_three_prints:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_one_print
    call compile_one_print
    call compile_one_print
    # Unknown variable: a
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: b
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: ab
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: c
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: total
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_three_prints
.size compile_three_prints, .-compile_three_prints

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    # print("1\n")
    leaq .str0(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str1(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str2(%rip), %rdi
    call puts@PLT
    call compile_three_prints
    # print("3\n")
    leaq .str3(%rip), %rdi
    call puts@PLT
    # print("0\n")
    leaq .str4(%rip), %rdi
    call puts@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "1\n"
.str1:
    .string "1\n"
.str2:
    .string "1\n"
.str3:
    .string "3\n"
.str4:
    .string "0\n"

.section .note.GNU-stack,"",@progbits
