; Generated by melpc bootstrap compiler
section .data
    msg_ok: db 'MELP Module OK',10,0


section .bss
    result1: resq 1
    result2: resq 1

section .text
    extern mlp_print
    extern mlp_malloc
    global _start

get_value:
    push rbp
    mov rbp, rsp
    mov rax, 100
    pop rbp
    ret

double_ten:
    push rbp
    mov rbp, rsp
    mov rax, 20
    pop rbp
    ret

_start:
    ; result1 = get_value()
    call get_value
    mov qword [result1], rax
    ; result2 = double_ten()
    call double_ten
    mov qword [result2], rax

    ; Print success message
    mov rdi, msg_ok
    call mlp_print

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
