# Main program: compiler/stage1/main.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.section .rodata
.div_zero_msg:
    .string "Division by zero is not allowed!"

.text


# Function: phase_lexer
.global phase_lexer
phase_lexer:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: source_code at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_0: .asciz "[PHASE 1] Lexer - Tokenization"
    .section .text
    leaq _str_0(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: tokens at -16(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize tokens

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_1: .asciz "  ✓ Tokenization complete"
    .section .text
    leaq _str_1(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -16(%rbp), %r8  # Load tokens
    movq %r8, %rax  # Return value
    jmp .Lphase_lexer_return

.Lphase_lexer_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: phase_parser
.global phase_parser
phase_parser:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: tokens at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_2: .asciz "[PHASE 2] Parser - AST Construction"
    .section .text
    leaq _str_2(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: ast at -16(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize ast

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_3: .asciz "  ✓ AST construction complete"
    .section .text
    leaq _str_3(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -16(%rbp), %r8  # Load ast
    movq %r8, %rax  # Return value
    jmp .Lphase_parser_return

.Lphase_parser_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: phase_codegen
.global phase_codegen
phase_codegen:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: ast at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_4: .asciz "[PHASE 3] CodeGen - LLVM IR Generation"
    .section .text
    leaq _str_4(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: llvm_ir at -16(%rbp)

.section .rodata
.str_0:
    .string ""
.text
    leaq .str_0(%rip), %r8  # Load string address
    movq %r8, -16(%rbp)  # Initialize llvm_ir

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_5: .asciz "  ✓ LLVM IR generation complete"
    .section .text
    leaq _str_5(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -16(%rbp), %r8  # Load llvm_ir
    movq %r8, %rax  # Return value
    jmp .Lphase_codegen_return

.Lphase_codegen_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: compile
.global compile
compile:
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp
    # Parameter: source_code at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_6: .asciz "========================================"
    .section .text
    leaq _str_6(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_7: .asciz "MELP Stage 1 Compiler"
    .section .text
    leaq _str_7(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_8: .asciz "========================================"
    .section .text
    leaq _str_8(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_9: .asciz ""
    .section .text
    leaq _str_9(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: tokens at -16(%rbp)

    # Arithmetic expression
    # Function call: phase_lexer()
    movq -8(%rbp), %r10  # Load source_code
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call phase_lexer
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize tokens
    # Variable: ast at -24(%rbp)

    # Arithmetic expression
    # Function call: phase_parser()
    movq -16(%rbp), %r10  # Load tokens
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call phase_parser
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Initialize ast
    # Variable: llvm_ir at -32(%rbp)

    # Arithmetic expression
    # Function call: phase_codegen()
    movq -24(%rbp), %r10  # Load ast
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call phase_codegen
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Initialize llvm_ir

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_10: .asciz ""
    .section .text
    leaq _str_10(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_11: .asciz "========================================"
    .section .text
    leaq _str_11(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_12: .asciz "Compilation Complete!"
    .section .text
    leaq _str_12(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_13: .asciz "========================================"
    .section .text
    leaq _str_13(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    movq -32(%rbp), %r8  # Load llvm_ir
    movq %r8, %rax  # Return value
    jmp .Lcompile_return

.Lcompile_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: main
.global main
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_14: .asciz "MELP Stage 1 - Bootstrap Test"
    .section .text
    leaq _str_14(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_15: .asciz "Modules loaded:"
    .section .text
    leaq _str_15(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_16: .asciz "  ✓ core (YZ_03)"
    .section .text
    leaq _str_16(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_17: .asciz "  ✓ functions (YZ_04)"
    .section .text
    leaq _str_17(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_18: .asciz "  ✓ variables (YZ_05)"
    .section .text
    leaq _str_18(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_19: .asciz "  ✓ operators (YZ_06)"
    .section .text
    leaq _str_19(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_20: .asciz "  ✓ control_flow (YZ_07)"
    .section .text
    leaq _str_20(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_21: .asciz "  ✓ literals (YZ_08)"
    .section .text
    leaq _str_21(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_22: .asciz "  ✓ arrays (YZ_09)"
    .section .text
    leaq _str_22(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_23: .asciz "  ✓ structs (YZ_10)"
    .section .text
    leaq _str_23(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_24: .asciz "  ✓ enums (YZ_11)"
    .section .text
    leaq _str_24(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_25: .asciz ""
    .section .text
    leaq _str_25(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: test_code at -8(%rbp)

.section .rodata
.str_1:
    .string "function test() returns numeric\n    return 42\nend_function"
.text
    leaq .str_1(%rip), %r8  # Load string address
    movq %r8, -8(%rbp)  # Initialize test_code
    # Variable: result at -16(%rbp)

    # Arithmetic expression
    # Function call: compile()
    movq -8(%rbp), %r10  # Load test_code
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call compile
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize result

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lmain_return

.Lmain_return:
    movq %rbp, %rsp
    popq %rbp
    ret
