# Generated by MELP Simple Codegen
.text

# Function: generate_add
.globl generate_add
.type generate_add, @function
generate_add:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_add
.size generate_add, .-generate_add

# Function: generate_sub
.globl generate_sub
.type generate_sub, @function
generate_sub:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_sub
.size generate_sub, .-generate_sub

# Function: generate_mul
.globl generate_mul
.type generate_mul, @function
generate_mul:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_mul
.size generate_mul, .-generate_mul

# Function: generate_div
.globl generate_div
.type generate_div, @function
generate_div:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_div
.size generate_div, .-generate_div

# Function: generate_literal
.globl generate_literal
.type generate_literal, @function
generate_literal:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param value
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_literal
.size generate_literal, .-generate_literal

# Function: generate_variable_load
.globl generate_variable_load
.type generate_variable_load, @function
generate_variable_load:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_variable_load
.size generate_variable_load, .-generate_variable_load

# Function: generate_variable_store
.globl generate_variable_store
.type generate_variable_store, @function
generate_variable_store:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_variable_store
.size generate_variable_store, .-generate_variable_store

# Function: compile_arithmetic_expr
.globl compile_arithmetic_expr
.type compile_arithmetic_expr, @function
compile_arithmetic_expr:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # return expression
    leave
    ret
    # end of compile_arithmetic_expr
.size compile_arithmetic_expr, .-compile_arithmetic_expr

# Function: compile_variable_decl
.globl compile_variable_decl
.type compile_variable_decl, @function
compile_variable_decl:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_arithmetic_expr
    movq %rax, -8(%rbp)  # store expr_result
    call generate_variable_store
    movq %rax, -16(%rbp)  # store store_result
    movq -8(%rbp), %rax  # load expr_result
    # return expression
    leave
    ret
    # end of compile_variable_decl
.size compile_variable_decl, .-compile_variable_decl

# Function: compile_arithmetic_test
.globl compile_arithmetic_test
.type compile_arithmetic_test, @function
compile_arithmetic_test:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $10, %rax
    pushq %rax  # save left operand
    movq $5, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -8(%rbp)  # store add
    movq $6, %rax
    pushq %rax  # save left operand
    movq $7, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    imulq %rbx, %rax
    movq %rax, -16(%rbp)  # store mul
    movq $0, %rax
    movq %rax, -24(%rbp)  # store count
    movq -24(%rbp), %rax  # load count
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -24(%rbp)  # update count
    movq -24(%rbp), %rax  # load count
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -24(%rbp)  # update count
    movq -24(%rbp), %rax  # load count
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -24(%rbp)  # update count
    movq -24(%rbp), %rax  # load count
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -24(%rbp)  # update count
    movq -24(%rbp), %rax  # load count
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_arithmetic_test
.size compile_arithmetic_test, .-compile_arithmetic_test

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str2(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str3(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    call compile_arithmetic_test
    movq %rax, -8(%rbp)  # store test_result
    movq -8(%rbp), %rax  # load test_result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str4(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"
.str1:
    .string "%ld\n"
.str2:
    .string "%ld\n"
.str3:
    .string "%ld\n"
.str4:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
