# Generated by MELP Simple Codegen
.text

# Function: compile_arithmetic_main
.globl compile_arithmetic_main
.type compile_arithmetic_main, @function
compile_arithmetic_main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store arith_status
    movq $1, %rax
    movq %rax, -8(%rbp)  # update arith_status
    movq -8(%rbp), %rax  # load arith_status
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -8(%rbp), %rax  # load arith_status
    # return expression
    leave
    ret
    # end of compile_arithmetic_main
.size compile_arithmetic_main, .-compile_arithmetic_main

# Function: compile_arithmetic_parser
.globl compile_arithmetic_parser
.type compile_arithmetic_parser, @function
compile_arithmetic_parser:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store parser_status
    movq $1, %rax
    movq %rax, -8(%rbp)  # update parser_status
    movq -8(%rbp), %rax  # load parser_status
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -8(%rbp), %rax  # load parser_status
    # return expression
    leave
    ret
    # end of compile_arithmetic_parser
.size compile_arithmetic_parser, .-compile_arithmetic_parser

# Function: compile_arithmetic_codegen
.globl compile_arithmetic_codegen
.type compile_arithmetic_codegen, @function
compile_arithmetic_codegen:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store codegen_status
    movq $1, %rax
    movq %rax, -8(%rbp)  # update codegen_status
    movq -8(%rbp), %rax  # load codegen_status
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str2(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -8(%rbp), %rax  # load codegen_status
    # return expression
    leave
    ret
    # end of compile_arithmetic_codegen
.size compile_arithmetic_codegen, .-compile_arithmetic_codegen

# Function: compile_arithmetic_module
.globl compile_arithmetic_module
.type compile_arithmetic_module, @function
compile_arithmetic_module:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_arithmetic_main
    movq %rax, -8(%rbp)  # store result1
    call compile_arithmetic_parser
    movq %rax, -16(%rbp)  # store result2
    call compile_arithmetic_codegen
    movq %rax, -24(%rbp)  # store result3
    movq -8(%rbp), %rax  # load result1
    pushq %rax  # save left operand
    movq -16(%rbp), %rax  # load result2
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -32(%rbp)  # store total
    movq -32(%rbp), %rax  # load total
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str3(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_arithmetic_module
.size compile_arithmetic_module, .-compile_arithmetic_module

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_arithmetic_module
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"
.str1:
    .string "%ld\n"
.str2:
    .string "%ld\n"
.str3:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
