# Generated by MELP Simple Codegen
.text

# Function: generate_add
.globl generate_add
.type generate_add, @function
generate_add:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_add
.size generate_add, .-generate_add

# Function: generate_sub
.globl generate_sub
.type generate_sub, @function
generate_sub:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_sub
.size generate_sub, .-generate_sub

# Function: generate_mul
.globl generate_mul
.type generate_mul, @function
generate_mul:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_mul
.size generate_mul, .-generate_mul

# Function: generate_div
.globl generate_div
.type generate_div, @function
generate_div:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_div
.size generate_div, .-generate_div

# Function: compile_one_op
.globl compile_one_op
.type compile_one_op, @function
compile_one_op:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call generate_add
    movq %rax, -16(%rbp)  # store code
    movq -16(%rbp), %rax  # load code
    # return expression
    leave
    ret
    # end of compile_one_op
.size compile_one_op, .-compile_one_op

# Function: compile_three_ops
.globl compile_three_ops
.type compile_three_ops, @function
compile_three_ops:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_one_op
    movq %rax, -16(%rbp)  # store a
    call compile_one_op
    movq %rax, -24(%rbp)  # store b
    call compile_one_op
    movq %rax, -32(%rbp)  # store c
    movq -16(%rbp), %rax  # load a
    pushq %rax  # save left operand
    movq -24(%rbp), %rax  # load b
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -40(%rbp)  # store ab
    movq -40(%rbp), %rax  # load ab
    pushq %rax  # save left operand
    movq -32(%rbp), %rax  # load c
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -48(%rbp)  # store total
    movq -48(%rbp), %rax  # load total
    # return expression
    leave
    ret
    # end of compile_three_ops
.size compile_three_ops, .-compile_three_ops

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    # print("1\n")
    leaq .str0(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str1(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str2(%rip), %rdi
    call puts@PLT
    call compile_three_ops
    movq %rax, -16(%rbp)  # store count
    # print("3\n")
    leaq .str3(%rip), %rdi
    call puts@PLT
    # print("0\n")
    leaq .str4(%rip), %rdi
    call puts@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "1\n"
.str1:
    .string "1\n"
.str2:
    .string "1\n"
.str3:
    .string "3\n"
.str4:
    .string "0\n"

.section .note.GNU-stack,"",@progbits
