# Generated by MELP Simple Codegen
.text

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str2(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $1, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str3(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str4(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"
.str1:
    .string "%ld\n"
.str2:
    .string "%ld\n"
.str3:
    .string "%ld\n"
.str4:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
