#include <stdio.h>
#include <stdlib.h>
#include "lexer.h"

// Modules
#include "modules/comments/comments.h"
#include "modules/variable/variable.h"
#include "modules/variable/variable_parser.h"
#include "modules/variable/variable_codegen.h"
#include "modules/arithmetic/arithmetic.h"
#include "modules/arithmetic/arithmetic_parser.h"
#include "modules/arithmetic/arithmetic_codegen.h"

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input.mlp> <output.s>\n", argv[0]);
        return 1;
    }
    
    // Read source file
    FILE* f = fopen(argv[1], "r");
    if (!f) {
        fprintf(stderr, "Error: Cannot open input file\n");
        return 1;
    }
    
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    char* source = malloc(size + 1);
    fread(source, 1, size, f);
    source[size] = '\0';
    fclose(f);
    
    // Create lexer
    Lexer* lexer = lexer_create(source);
    
    // Create parser
    VariableParser* parser = variable_parser_create(lexer);
    
    // Open output file
    FILE* out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "Error: Cannot create output file\n");
        return 1;
    }
    
    // Create codegen
    VariableCodegen* codegen = variable_codegen_create(out);
    
    // Write assembly header
    fprintf(out, "; Generated by MELP Stage 0 Compiler\n");
    fprintf(out, "global _start\n\n");
    
    // Parse and generate code for declarations
    printf("=== VARIABLE MODULE TEST ===\n");
    int decl_count = 0;
    
    while (parser->current_token && parser->current_token->type != TOKEN_EOF) {
        VariableDeclaration* decl = variable_parse_declaration(parser);
        
        if (decl) {
            printf("Parsed: %s = %s\n", decl->name, decl->value);
            variable_codegen_declaration(codegen, decl);
            variable_declaration_free(decl);
            decl_count++;
        } else {
            // Skip unknown tokens
            if (parser->current_token) {
                token_free(parser->current_token);
                parser->current_token = lexer_next_token(lexer);
            }
        }
    }
    
    // Write minimal _start
    fprintf(out, "\nsection .text\n");
    fprintf(out, "_start:\n");
    fprintf(out, "    ; Exit program\n");
    fprintf(out, "    mov rax, 60     ; sys_exit\n");
    fprintf(out, "    xor rdi, rdi    ; status 0\n");
    fprintf(out, "    syscall\n");
    
    printf("\n✅ Variable module test passed!\n");
    printf("Parsed %d variable declarations.\n", decl_count);
    printf("Assembly code generated: %s\n", argv[2]);
    
    fclose(out);
    variable_codegen_free(codegen);
    variable_parser_free(parser);
    free(source);
    
    return 0;
}
