# Generated by MELP Codegen Compiler - Stage 0
# GC Integration: malloc calls redirected to gc_alloc

.section .text

.globl main
main:
    pushq %rbp
    movq %rsp, %rbp

    # Example: Allocate using GC
    movq $16, %rdi
    call gc_alloc

    # Return 0
    movq $0, %rax
    movq %rbp, %rsp
    popq %rbp
    ret
