# Main program: /tmp/test_partial.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.section .rodata
.div_zero_msg:
    .string "Division by zero is not allowed!"

.text


# Function: token_to_param_type
.global token_to_param_type
token_to_param_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: token_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_1
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_PARAM_NUMERIC
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return
.if_end_1:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING_TYPE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_3
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_PARAM_TEXT
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return
.if_end_3:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_5
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_PARAM_TEXT
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return
.if_end_5:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_BOOLEAN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_7
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_PARAM_BOOLEAN
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return
.if_end_7:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_LIST
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_9
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_PARAM_LIST
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return
.if_end_9:
    movq 0(%rbp), %r8  # Load FUNC_PARAM_NUMERIC
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_param_type_return

.Ltoken_to_param_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: token_to_return_type
.global token_to_return_type
token_to_return_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: token_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_11
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_RETURN_NUMERIC
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_return_type_return
.if_end_11:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING_TYPE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_13
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_RETURN_TEXT
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_return_type_return
.if_end_13:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_15
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_RETURN_TEXT
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_return_type_return
.if_end_15:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_BOOLEAN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_17
    # Then body
    movq 0(%rbp), %r8  # Load FUNC_RETURN_BOOLEAN
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_return_type_return
.if_end_17:
    movq 0(%rbp), %r8  # Load FUNC_RETURN_VOID
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_return_type_return

.Ltoken_to_return_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: parse_function_declaration
.global parse_function_declaration
parse_function_declaration:
    pushq %rbp
    movq %rsp, %rbp
    subq $152, %rsp
    # Parameter: tokens at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: pos at -16(%rbp)
    movq %rsi, -16(%rbp)
    # Variable: func_name at -24(%rbp)

.section .rodata
.str_0:
    .string ""
.text
    leaq .str_0(%rip), %r8  # Load string address
    movq %r8, -24(%rbp)  # Initialize func_name
    # Variable: params at -32(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Initialize params
    # Variable: return_type at -40(%rbp)

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load FUNC_RETURN_VOID
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Initialize return_type
    # Variable: body at -48(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -48(%rbp)  # Initialize body
    # Variable: current_pos at -56(%rbp)

    # Arithmetic expression
    movq -16(%rbp), %r8  # Load pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Initialize current_pos
    # Variable: current_token at -64(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Initialize current_token
    # Variable: token_type at -72(%rbp)

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Initialize token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_FUNCTION
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_19
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_19:
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_0
    jmp .no_overflow_0
.overflow_detected_0:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_0:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_21
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_21:
    # Assignment: func_name = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to func_name
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_1
    jmp .no_overflow_1
.overflow_detected_1:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_1:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_LPAREN
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_23
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_23:
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_2
    jmp .no_overflow_2
.overflow_detected_2:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_2:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_RPAREN
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_25
    # Then body
    # Variable: param_type at -80(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -80(%rbp)  # Initialize param_type
    # Variable: param_name at -88(%rbp)

.section .rodata
.str_1:
    .string ""
.text
    leaq .str_1(%rip), %r8  # Load string address
    movq %r8, -88(%rbp)  # Initialize param_name
    # Variable: parsing_params at -96(%rbp)
    movq $1, %r8  # Literal value
    movq %r8, -96(%rbp)  # Initialize parsing_params

    # While loop
.while_start_26:

    # Comparison with logical chaining
    movq -96(%rbp), %r8  # Load parsing_params
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .loop_end_26
    # Loop body
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: param_type = ...

    # Arithmetic expression
    # Function call: token_to_param_type()
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r10  # Array element value
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call token_to_param_type
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -80(%rbp)  # Store to param_type
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_3
    jmp .no_overflow_3
.overflow_detected_3:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_3:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Variable: token_type_check at -104(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -104(%rbp)  # Initialize token_type_check
    # Assignment: token_type_check = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to token_type_check

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load token_type_check
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_28
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_28:
    # Assignment: param_name = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Store to param_name
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_4
    jmp .no_overflow_4
.overflow_detected_4:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_4:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Variable: param at -112(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -80(%rbp), %r8  # Load param_type
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -88(%rbp), %r8  # Load param_name
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -112(%rbp)  # Initialize param
    # Assignment: params = ...

    # Arithmetic expression
    movq -32(%rbp), %r8  # Load params
    # Collection literal
    # Array literal: 1 elements, type=0
    # Allocate array on heap
    movq $1, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -112(%rbp), %r8  # Load param
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r9  # Collection pointer
    addq %r9, %r8
    jo .overflow_detected_5
    jmp .no_overflow_5
.overflow_detected_5:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_5:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Store to params
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_COMMA
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_29
    # Then body
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_6
    jmp .no_overflow_6
.overflow_detected_6:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_6:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    jmp .if_end_30
.if_else_29:
    # Else body

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_RPAREN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_31
    # Then body
    # Assignment: parsing_params = ...

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to parsing_params
    jmp .if_end_32
.if_else_31:
    # Else body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_32:
.if_end_30:
    jmp .while_start_26
.loop_end_26:
.if_end_25:
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Variable: token_type_paren at -120(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -120(%rbp)  # Initialize token_type_paren
    # Assignment: token_type_paren = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -120(%rbp)  # Store to token_type_paren

    # If statement

    # Comparison with logical chaining
    movq -120(%rbp), %r8  # Load token_type_paren
    movq 0(%rbp), %r9  # Load TOKEN_RPAREN
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_34
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_34:
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_7
    jmp .no_overflow_7
.overflow_detected_7:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_7:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_RETURNS
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_36
    # Then body
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_8
    jmp .no_overflow_8
.overflow_detected_8:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_8:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: return_type = ...

    # Arithmetic expression
    # Function call: token_to_return_type()
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r10  # Array element value
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call token_to_return_type
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Store to return_type
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_9
    jmp .no_overflow_9
.overflow_detected_9:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_9:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_36:
    # Variable: body_start at -128(%rbp)

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Initialize body_start
    # Variable: found_end at -136(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -136(%rbp)  # Initialize found_end

    # While loop
.while_start_37:

    # Comparison with logical chaining
    movq -136(%rbp), %r8  # Load found_end
    movq $0, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .loop_end_37
    # Loop body
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Assignment: token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to token_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_END
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_39
    # Then body
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_10
    jmp .no_overflow_10
.overflow_detected_10:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_10:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Assignment: current_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to current_token
    # Variable: next_token_type at -144(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -144(%rbp)  # Initialize next_token_type
    # Assignment: next_token_type = ...

    # Arithmetic expression
    # Array index access: current_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -144(%rbp)  # Store to next_token_type

    # If statement

    # Comparison with logical chaining
    movq -144(%rbp), %r8  # Load next_token_type
    movq 0(%rbp), %r9  # Load TOKEN_FUNCTION
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_40
    # Then body
    # Assignment: found_end = ...

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to found_end
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_11
    jmp .no_overflow_11
.overflow_detected_11:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_11:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    jmp .if_end_41
.if_else_40:
    # Else body
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_12
    jmp .no_overflow_12
.overflow_detected_12:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_12:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_41:

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_EOF
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_43
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
.if_end_43:
.if_end_39:
    # Variable: func_decl at -152(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 5 elements, type=0
    # Allocate array on heap
    movq $5, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -24(%rbp), %r8  # Load func_name
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -32(%rbp), %r8  # Load params
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -40(%rbp), %r8  # Load return_type
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq -128(%rbp), %r8  # Load body_start
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    # Element 4
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $2, %r9  # Literal
    subq %r9, %r8
    jo .overflow_detected_13
    jmp .no_overflow_13
.overflow_detected_13:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_sub
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_13:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 32(%rbx)  # Store element at index 4
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -152(%rbp)  # Initialize func_decl

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -152(%rbp), %r8  # Load func_decl
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_function_declaration_return
    jmp .while_start_37
.loop_end_37:

.Lparse_function_declaration_return:
    movq %rbp, %rsp
    popq %rbp
    ret
