# Module: archive/stage1_api_attempt/modules/variables/variables_parser.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.text


# Function: token_to_var_type
.global token_to_var_type
token_to_var_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: token_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_1
    # Then body
    movq 0(%rbp), %r8  # Load VAR_NUMERIC
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_1:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING_TYPE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_3
    # Then body
    movq 0(%rbp), %r8  # Load VAR_STRING
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_3:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_BOOLEAN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_5
    # Then body
    movq 0(%rbp), %r8  # Load VAR_BOOLEAN
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_5:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_ARRAY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_7
    # Then body
    movq 0(%rbp), %r8  # Load VAR_ARRAY
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_7:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_LIST
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_9
    # Then body
    movq 0(%rbp), %r8  # Load VAR_LIST
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_9:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_TUPLE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_11
    # Then body
    movq 0(%rbp), %r8  # Load VAR_TUPLE
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return
.if_end_11:

    # Arithmetic expression
    movq $-1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltoken_to_var_type_return

.Ltoken_to_var_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_type_token
.global is_type_token
is_type_token:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: token_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_13
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_13:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING_TYPE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_15
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_15:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_BOOLEAN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_17
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_17:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_ARRAY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_19
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_19:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_LIST
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_21
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_21:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_TUPLE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_23
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return
.if_end_23:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_type_token_return

.Lis_type_token_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: parse_variable_declaration
.global parse_variable_declaration
parse_variable_declaration:
    pushq %rbp
    movq %rsp, %rbp
    subq $184, %rsp
    # Parameter: tokens at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: pos at -16(%rbp)
    movq %rsi, -16(%rbp)
    # Variable: tokens_len at -24(%rbp)

    # Arithmetic expression
    # Member access: tokens.length
    # ERROR: Instance 'tokens' not found
    xor %r8, %r8  # Error fallback
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Initialize tokens_len

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_25
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_25:
    # Variable: type_token at -32(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -16(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Initialize type_token
    # Variable: token_type at -40(%rbp)

    # Arithmetic expression
    # Array index access: type_token
    movq -32(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Initialize token_type
    # Variable: base_type at -48(%rbp)

    # Arithmetic expression
    # Function call: token_to_var_type()
    movq -40(%rbp), %r10  # Load token_type
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call token_to_var_type
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -48(%rbp)  # Initialize base_type

    # If statement

    # Comparison with logical chaining
    movq -48(%rbp), %r8  # Load base_type
    movq $-1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_27
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_27:
    # Variable: current_pos at -56(%rbp)

    # Arithmetic expression
    movq -16(%rbp), %r8  # Load pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_0
    jmp .no_overflow_0
.overflow_detected_0:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_0:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Initialize current_pos
    # Variable: is_pointer at -64(%rbp)
    movq $false, %r8  # Literal value
    movq %r8, -64(%rbp)  # Initialize is_pointer
    # Variable: is_array at -72(%rbp)
    movq $false, %r8  # Literal value
    movq %r8, -72(%rbp)  # Initialize is_array
    # Variable: array_size at -80(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -80(%rbp)  # Initialize array_size
    # Variable: actual_type at -88(%rbp)

    # Arithmetic expression
    movq -48(%rbp), %r8  # Load base_type
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Initialize actual_type

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_29
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_29:
    # Variable: next_token at -96(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Initialize next_token
    # Variable: next_type at -104(%rbp)

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Initialize next_type

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load next_type
    movq 0(%rbp), %r9  # Load TOKEN_MULTIPLY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_31
    # Then body
    # Assignment: is_pointer = ...

    # Arithmetic expression
    movq $1, %r8  # Boolean literal: true
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Store to is_pointer
    # Assignment: actual_type = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load VAR_POINTER
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Store to actual_type
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_1
    jmp .no_overflow_1
.overflow_detected_1:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_1:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_33
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_33:
    # Assignment: next_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to next_token
    # Assignment: next_type = ...

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to next_type
.if_end_31:

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load next_type
    movq 0(%rbp), %r9  # Load TOKEN_LBRACKET
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_35
    # Then body
    # Assignment: is_array = ...

    # Arithmetic expression
    movq $1, %r8  # Boolean literal: true
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Store to is_array
    # Assignment: actual_type = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load VAR_ARRAY
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Store to actual_type
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_2
    jmp .no_overflow_2
.overflow_detected_2:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_2:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_37
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_37:
    # Assignment: next_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to next_token
    # Assignment: next_type = ...

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to next_type

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load next_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMBER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_39
    # Then body
    # Variable: size_str at -112(%rbp)

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -112(%rbp)  # Initialize size_str
    # Assignment: array_size = ...

    # Arithmetic expression
    # Function call: numeric()
    movq -112(%rbp), %r10  # Load size_str
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call numeric
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -80(%rbp)  # Store to array_size
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_3
    jmp .no_overflow_3
.overflow_detected_3:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_3:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_41
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_41:
    # Assignment: next_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to next_token
    # Assignment: next_type = ...

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to next_type
.if_end_39:

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load next_type
    movq 0(%rbp), %r9  # Load TOKEN_RBRACKET
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_43
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_43:
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_4
    jmp .no_overflow_4
.overflow_detected_4:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_4:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_45
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_45:
    # Assignment: next_token = ...

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to next_token
    # Assignment: next_type = ...

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to next_type
.if_end_35:

    # If statement

    # Comparison with logical chaining
    movq -104(%rbp), %r8  # Load next_type
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_47
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_47:
    # Variable: var_name at -120(%rbp)

    # Arithmetic expression
    # Array index access: next_token
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -120(%rbp)  # Initialize var_name
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_5
    jmp .no_overflow_5
.overflow_detected_5:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_5:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    # Variable: init_value at -128(%rbp)

.section .rodata
.str_0:
    .string ""
.text
    leaq .str_0(%rip), %r8  # Load string address
    movq %r8, -128(%rbp)  # Initialize init_value
    # Variable: storage_loc at -136(%rbp)

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_BSS
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Initialize storage_loc
    # Variable: has_initializer at -144(%rbp)
    movq $false, %r8  # Literal value
    movq %r8, -144(%rbp)  # Initialize has_initializer

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setl %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_49
    # Then body
    # Variable: assign_token at -152(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -152(%rbp)  # Initialize assign_token
    # Variable: assign_type at -160(%rbp)

    # Arithmetic expression
    # Array index access: assign_token
    movq -152(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -160(%rbp)  # Initialize assign_type

    # If statement

    # Comparison with logical chaining
    movq -160(%rbp), %r8  # Load assign_type
    movq 0(%rbp), %r9  # Load TOKEN_ASSIGN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_51
    # Then body
    # Assignment: has_initializer = ...

    # Arithmetic expression
    movq $1, %r8  # Boolean literal: true
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -144(%rbp)  # Store to has_initializer
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_6
    jmp .no_overflow_6
.overflow_detected_6:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_6:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_53
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return
.if_end_53:
    # Variable: value_token at -168(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -168(%rbp)  # Initialize value_token
    # Variable: value_type at -176(%rbp)

    # Arithmetic expression
    # Array index access: value_token
    movq -168(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -176(%rbp)  # Initialize value_type

    # If statement

    # Comparison with logical chaining
    movq -176(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMBER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_55
    # Then body
    # Assignment: init_value = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -168(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_DATA
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_7
    jmp .no_overflow_7
.overflow_detected_7:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_7:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_55:

    # If statement

    # Comparison with logical chaining
    movq -176(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_57
    # Then body
    # Assignment: init_value = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -168(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_DATA
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_8
    jmp .no_overflow_8
.overflow_detected_8:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_8:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_57:

    # If statement

    # Comparison with logical chaining
    movq -176(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_TRUE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_59
    # Then body
    # Assignment: init_value = ...

    # Arithmetic expression
    .section .rodata
    _str_0: .asciz "true"
    .section .text
    leaq _str_0(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_DATA
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_9
    jmp .no_overflow_9
.overflow_detected_9:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_9:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_59:

    # If statement

    # Comparison with logical chaining
    movq -176(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_FALSE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_61
    # Then body
    # Assignment: init_value = ...

    # Arithmetic expression
    .section .rodata
    _str_1: .asciz "false"
    .section .text
    leaq _str_1(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_DATA
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_10
    jmp .no_overflow_10
.overflow_detected_10:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_10:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_61:

    # If statement

    # Comparison with logical chaining
    movq -176(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_62
    # Then body
    # Assignment: init_value = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -168(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_BSS
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_11
    jmp .no_overflow_11
.overflow_detected_11:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_11:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    jmp .if_end_63
.if_else_62:
    # Else body
    # Assignment: init_value = ...

    # Arithmetic expression
    .section .rodata
    _str_2: .asciz ""
    .section .text
    leaq _str_2(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Store to init_value
    # Assignment: storage_loc = ...

    # Arithmetic expression
    movq 0(%rbp), %r8  # Load STORAGE_BSS
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Store to storage_loc
.if_end_63:
.if_end_51:
.if_end_49:
    # Variable: decl_info at -184(%rbp)
    # List decl_info registered: 9 elements

    # Arithmetic expression
    # Collection literal
    # List literal: 9 elements (heterogeneous)
    # Allocate list
    movq $16, %rdi  # Capacity
    call sto_list_alloc  # Returns list pointer in rax
    movq %rax, %rbx  # Save list pointer in rbx
    # Initialize list elements
    # List element 0 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -120(%rbp), %r8  # Load var_name
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $0, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 1 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -88(%rbp), %r8  # Load actual_type
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $1, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 2 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -128(%rbp), %r8  # Load init_value
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $2, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 3 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -136(%rbp), %r8  # Load storage_loc
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $3, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 4 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -64(%rbp), %r8  # Load is_pointer
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $4, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 5 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -72(%rbp), %r8  # Load is_array
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $5, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 6 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -80(%rbp), %r8  # Load array_size
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $6, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 7 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -48(%rbp), %r8  # Load base_type
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $7, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 8 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -144(%rbp), %r8  # Load has_initializer
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $8, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    movq %rbx, %rax  # List pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -184(%rbp)  # Initialize decl_info

    # Arithmetic expression
    # Collection literal
    # List literal: 2 elements (heterogeneous)
    # Allocate list
    movq $4, %rdi  # Capacity
    call sto_list_alloc  # Returns list pointer in rax
    movq %rax, %rbx  # Save list pointer in rbx
    # Initialize list elements
    # List element 0 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -184(%rbp), %r8  # Load decl_info
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $0, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 1 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $1, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    movq %rbx, %rax  # List pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_declaration_return

.Lparse_variable_declaration_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: parse_variable_assignment
.global parse_variable_assignment
parse_variable_assignment:
    pushq %rbp
    movq %rsp, %rbp
    subq $112, %rsp
    # Parameter: tokens at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: pos at -16(%rbp)
    movq %rsi, -16(%rbp)
    # Variable: tokens_len at -24(%rbp)

    # Arithmetic expression
    # Member access: tokens.length
    # ERROR: Instance 'tokens' not found
    xor %r8, %r8  # Error fallback
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Initialize tokens_len

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_65
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return
.if_end_65:
    # Variable: id_token at -32(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -16(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Initialize id_token
    # Variable: token_type at -40(%rbp)

    # Arithmetic expression
    # Array index access: id_token
    movq -32(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Initialize token_type

    # If statement

    # Comparison with logical chaining
    movq -40(%rbp), %r8  # Load token_type
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_67
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return
.if_end_67:
    # Variable: var_name at -48(%rbp)

    # Arithmetic expression
    # Array index access: id_token
    movq -32(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -48(%rbp)  # Initialize var_name
    # Variable: current_pos at -56(%rbp)

    # Arithmetic expression
    movq -16(%rbp), %r8  # Load pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_12
    jmp .no_overflow_12
.overflow_detected_12:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_12:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Initialize current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_69
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return
.if_end_69:
    # Variable: assign_token at -64(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Initialize assign_token
    # Variable: assign_type at -72(%rbp)

    # Arithmetic expression
    # Array index access: assign_token
    movq -64(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Initialize assign_type

    # If statement

    # Comparison with logical chaining
    movq -72(%rbp), %r8  # Load assign_type
    movq 0(%rbp), %r9  # Load TOKEN_ASSIGN
    cmpq %r9, %r8
    movq $0, %rax
    setne %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_71
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return
.if_end_71:
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_13
    jmp .no_overflow_13
.overflow_detected_13:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_13:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos

    # If statement

    # Comparison with logical chaining
    movq -56(%rbp), %r8  # Load current_pos
    movq -24(%rbp), %r9  # Load tokens_len
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_73
    # Then body

    # Arithmetic expression
    # Collection literal
    # Array literal: 0 elements, type=0
    # Allocate array on heap
    movq $0, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return
.if_end_73:
    # Variable: value_token at -80(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -8(%rbp), %rbx  # Load array pointer
    movq -56(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -80(%rbp)  # Initialize value_token
    # Variable: value_type at -88(%rbp)

    # Arithmetic expression
    # Array index access: value_token
    movq -80(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Initialize value_type
    # Variable: value_str at -96(%rbp)

.section .rodata
.str_1:
    .string ""
.text
    leaq .str_1(%rip), %r8  # Load string address
    movq %r8, -96(%rbp)  # Initialize value_str
    # Variable: is_expression at -104(%rbp)
    movq $false, %r8  # Literal value
    movq %r8, -104(%rbp)  # Initialize is_expression

    # If statement

    # Comparison with logical chaining
    movq -88(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_NUMBER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_75
    # Then body
    # Assignment: value_str = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -80(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to value_str
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_14
    jmp .no_overflow_14
.overflow_detected_14:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_14:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_75:

    # If statement

    # Comparison with logical chaining
    movq -88(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_77
    # Then body
    # Assignment: value_str = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -80(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to value_str
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_15
    jmp .no_overflow_15
.overflow_detected_15:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_15:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_77:

    # If statement

    # Comparison with logical chaining
    movq -88(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_TRUE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_79
    # Then body
    # Assignment: value_str = ...

    # Arithmetic expression
    .section .rodata
    _str_3: .asciz "true"
    .section .text
    leaq _str_3(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to value_str
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_16
    jmp .no_overflow_16
.overflow_detected_16:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_16:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_79:

    # If statement

    # Comparison with logical chaining
    movq -88(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_FALSE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_81
    # Then body
    # Assignment: value_str = ...

    # Arithmetic expression
    .section .rodata
    _str_4: .asciz "false"
    .section .text
    leaq _str_4(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to value_str
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_17
    jmp .no_overflow_17
.overflow_detected_17:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_17:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
.if_end_81:

    # If statement

    # Comparison with logical chaining
    movq -88(%rbp), %r8  # Load value_type
    movq 0(%rbp), %r9  # Load TOKEN_IDENTIFIER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_82
    # Then body
    # Assignment: value_str = ...

    # Arithmetic expression
    # Array index access: value_token
    movq -80(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Store to value_str
    # Assignment: current_pos = ...

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    movq $1, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_18
    jmp .no_overflow_18
.overflow_detected_18:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_18:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Store to current_pos
    jmp .if_end_83
.if_else_82:
    # Else body
    # Assignment: is_expression = ...

    # Arithmetic expression
    movq $1, %r8  # Boolean literal: true
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Store to is_expression
.if_end_83:
    # Variable: assign_info at -112(%rbp)
    # List assign_info registered: 3 elements

    # Arithmetic expression
    # Collection literal
    # List literal: 3 elements (heterogeneous)
    # Allocate list
    movq $4, %rdi  # Capacity
    call sto_list_alloc  # Returns list pointer in rax
    movq %rax, %rbx  # Save list pointer in rbx
    # Initialize list elements
    # List element 0 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -48(%rbp), %r8  # Load var_name
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $0, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 1 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -96(%rbp), %r8  # Load value_str
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $1, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 2 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -104(%rbp), %r8  # Load is_expression
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $2, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    movq %rbx, %rax  # List pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -112(%rbp)  # Initialize assign_info

    # Arithmetic expression
    # Collection literal
    # List literal: 2 elements (heterogeneous)
    # Allocate list
    movq $4, %rdi  # Capacity
    call sto_list_alloc  # Returns list pointer in rax
    movq %rax, %rbx  # Save list pointer in rbx
    # Initialize list elements
    # List element 0 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -112(%rbp), %r8  # Load assign_info
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $0, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    # List element 1 (type=0)
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load current_pos
    # Result in r8 (integer) or xmm0 (float)
    pushq %r8  # Push value to stack
    movq %rsp, %rdx  # arg3: pointer to value on stack
    movq 8(%rsp), %rbx  # Load list pointer (skipping value)
    movq %rbx, %rdi  # arg1: list pointer
    movq $1, %rsi  # arg2: index
    movq $0, %rcx  # arg4: type
    call sto_list_set  # Set element with type
    addq $16, %rsp  # Pop value and saved list pointer
    movq %rbx, %rax  # List pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lparse_variable_assignment_return

.Lparse_variable_assignment_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: get_var_type_name
.global get_var_type_name
get_var_type_name:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: var_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_NUMERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_85
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_5: .asciz "numeric"
    .section .text
    leaq _str_5(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_85:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_87
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_6: .asciz "string"
    .section .text
    leaq _str_6(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_87:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_BOOLEAN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_89
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_7: .asciz "boolean"
    .section .text
    leaq _str_7(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_89:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_POINTER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_91
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_8: .asciz "pointer"
    .section .text
    leaq _str_8(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_91:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_ARRAY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_93
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_9: .asciz "array"
    .section .text
    leaq _str_9(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_93:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_LIST
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_95
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_10: .asciz "list"
    .section .text
    leaq _str_10(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_95:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load var_type
    movq 0(%rbp), %r9  # Load VAR_TUPLE
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_96
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_11: .asciz "tuple"
    .section .text
    leaq _str_11(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
    jmp .if_end_97
.if_else_96:
    # Else body

    # Arithmetic expression
    .section .rodata
    _str_12: .asciz "unknown"
    .section .text
    leaq _str_12(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_var_type_name_return
.if_end_97:

.Lget_var_type_name_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: get_storage_name
.global get_storage_name
get_storage_name:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: storage at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load storage
    movq 0(%rbp), %r9  # Load STORAGE_REGISTER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_99
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_13: .asciz "register"
    .section .text
    leaq _str_13(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
.if_end_99:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load storage
    movq 0(%rbp), %r9  # Load STORAGE_STACK
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_101
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_14: .asciz "stack"
    .section .text
    leaq _str_14(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
.if_end_101:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load storage
    movq 0(%rbp), %r9  # Load STORAGE_DATA
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_103
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_15: .asciz "data"
    .section .text
    leaq _str_15(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
.if_end_103:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load storage
    movq 0(%rbp), %r9  # Load STORAGE_BSS
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_105
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_16: .asciz "bss"
    .section .text
    leaq _str_16(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
.if_end_105:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load storage
    movq 0(%rbp), %r9  # Load STORAGE_HEAP
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_else_106
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_17: .asciz "heap"
    .section .text
    leaq _str_17(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
    jmp .if_end_107
.if_else_106:
    # Else body

    # Arithmetic expression
    .section .rodata
    _str_18: .asciz "unknown"
    .section .text
    leaq _str_18(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_storage_name_return
.if_end_107:

.Lget_storage_name_return:
    movq %rbp, %rsp
    popq %rbp
    ret
