; Generated by MLP 26-Module Compiler
; Source: merhaba.mlp

global _start

section .data
    str_1 db "Hello World!!!", 10
    str_1_len equ $ - str_1

section .text
_start:
    ; Print string 1
    mov rax, 1
    mov rdi, 1
    lea rsi, [str_1]
    mov rdx, str_1_len
    syscall

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
