; Generated by MELP Stage 0 Compiler
global _start

    ; Variable: g_source (type: text)
    ; TTO: SSO optimization (≤23 chars)

section .data
    var_g_source: db "", 0  ; Small string inline
    ; Variable: g_pos (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_g_pos: resq 1  ; 64-bit integer

section .text
    mov rax, 0
    mov [var_g_pos], rax
    ; Variable: g_line (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_g_line: resq 1  ; 64-bit integer

section .text
    mov rax, 1
    mov [var_g_line], rax
    ; Variable: g_source_len (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_g_source_len: resq 1  ; 64-bit integer

section .text
    mov rax, 0
    mov [var_g_source_len], rax
    ; Variable: g_token_type (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_g_token_type: resq 1  ; 64-bit integer

section .text
    mov rax, 0
    mov [var_g_token_type], rax
    ; Variable: g_token_value (type: text)
    ; TTO: SSO optimization (≤23 chars)

section .data
    var_g_token_value: db "", 0  ; Small string inline
    ; Variable: g_token_line (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_g_token_line: resq 1  ; 64-bit integer

section .text
    mov rax, 1
    mov [var_g_token_line], rax
    ; Variable: has_dot (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_has_dot: resq 1  ; 64-bit integer

section .text
    mov rax, 0
    mov [var_has_dot], rax

section .text
_start:
    ; Exit program
    mov rax, 60     ; sys_exit
    xor rdi, rdi    ; status 0
    syscall
