# Generated by MELP Simple Codegen
.text

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $5, %rax
    movq %rax, -16(%rbp)  # store a
    movq $3, %rax
    movq %rax, -24(%rbp)  # store b
    movq -16(%rbp), %rax  # load a
    pushq %rax  # save left operand
    movq -24(%rbp), %rax  # load b
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -32(%rbp)  # store result
    movq -32(%rbp), %rax  # load result
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata

.section .note.GNU-stack,"",@progbits
