# Generated by MELP Simple Codegen
.text

# Function: factorial
.globl factorial
.type factorial, @function
factorial:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param n
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load n
    pushq %rax
    movq $1, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setle %al  # <=
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse0  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend1  # skip else
.Lelse0:
.Lend1:
    movq -8(%rbp), %rax  # load n
    pushq %rax  # save left operand
    movq -8(%rbp), %rax  # load n
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    subq %rbx, %rax
    movq %rax, %rdi  # arg 0
    call factorial
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    imulq %rbx, %rax
    # return expression
    leave
    ret
    # end of factorial
.size factorial, .-factorial

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $5, %rax
    movq %rax, %rdi  # arg 0
    call factorial
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
