# Generated by MELP Simple Codegen
.text

# Function: make_number
.globl make_number
.type make_number, @function
make_number:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param val
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load val
    pushq %rax  # save left operand
    movq $10, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # return expression
    leave
    ret
    # end of make_number
.size make_number, .-make_number

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $42, %rax
    movq %rax, %rdi  # arg 0
    call make_number
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
