# Generated by MELP Simple Codegen
.text

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $10, %rax
    movq %rax, -8(%rbp)  # store x
    movq -8(%rbp), %rax  # load x
    pushq %rax
    movq $5, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setg %al  # >
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse0  # if false, jump to else
    # print("x is greater than 5")
    leaq .str0(%rip), %rdi
    call puts@PLT
    jmp .Lend1  # skip else
.Lelse0:
.Lend1:
    movq $0, %rax
    movq %rax, -16(%rbp)  # store i
.Lloop2:  # while loop start
    movq -16(%rbp), %rax  # load i
    pushq %rax
    movq $3, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setl %al  # <
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lend3  # exit loop if false
    movq -16(%rbp), %rax  # load i
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -16(%rbp), %rax  # load i
    pushq %rax  # save left operand
    movq $1, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -16(%rbp)  # update i
    jmp .Lloop2  # loop back
.Lend3:  # while loop end
    # return 0
    movq $0, %rax
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "x is greater than 5"
.str1:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
