# Generated by MELP Simple Codegen
.text

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    # print("Hello World")
    leaq .str0(%rip), %rdi
    call puts@PLT
    # return 0
    movq $0, %rax
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "Hello World"

.section .note.GNU-stack,"",@progbits
