# Module: /tmp/melp_test/lib/math.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.text


# Function: lib_multiply
.global lib_multiply
lib_multiply:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: a at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: b at -16(%rbp)
    movq %rsi, -16(%rbp)

    # Arithmetic expression
    movq -8(%rbp), %r8  # Load a
    movq -16(%rbp), %r9  # Load b
    imulq %r9, %r8
    jo .overflow_detected_0
    jmp .no_overflow_0
.overflow_detected_0:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_mul
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_0:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Llib_multiply_return

.Llib_multiply_return:
    movq %rbp, %rsp
    popq %rbp
    ret
