# Module: /tmp/melp_test2/shared/utils.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.text


# Function: shared_square
.global shared_square
shared_square:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: x at -8(%rbp)
    movq %rdi, -8(%rbp)

    # Arithmetic expression
    movq -8(%rbp), %r8  # Load x
    movq -8(%rbp), %r9  # Load x
    imulq %r9, %r8
    jo .overflow_detected_0
    jmp .no_overflow_0
.overflow_detected_0:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_mul
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_0:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lshared_square_return

.Lshared_square_return:
    movq %rbp, %rsp
    popq %rbp
    ret
