; Generated by melpc bootstrap compiler
section .data
    msg_ok: db 'MELP Module OK',10,0

section .bss
    and_true_true: resq 1
    and_true_false: resq 1
    and_false_false: resq 1
    or_true_true: resq 1
    or_true_false: resq 1
    or_false_false: resq 1
    not_true: resq 1
    not_false: resq 1

section .text
    extern mlp_print
    extern mlp_malloc
    global _start

_start:
    ; and_true_true = true AND true
    mov rax, 1
    mov rbx, 1
    and rax, rbx
    mov qword [and_true_true], rax
    ; and_true_false = true AND false
    mov rax, 1
    mov rbx, 0
    and rax, rbx
    mov qword [and_true_false], rax
    ; and_false_false = false AND false
    mov rax, 0
    mov rbx, 0
    and rax, rbx
    mov qword [and_false_false], rax
    ; or_true_true = true OR true
    mov rax, 1
    mov rbx, 1
    or rax, rbx
    mov qword [or_true_true], rax
    ; or_true_false = true OR false
    mov rax, 1
    mov rbx, 0
    or rax, rbx
    mov qword [or_true_false], rax
    ; or_false_false = false OR false
    mov rax, 0
    mov rbx, 0
    or rax, rbx
    mov qword [or_false_false], rax
    ; not_true = NOT true
    mov rax, 1
    xor rax, 1
    mov qword [not_true], rax
    ; not_false = NOT false
    mov rax, 0
    xor rax, 1
    mov qword [not_false], rax

    ; Print success message
    mov rdi, msg_ok
    call mlp_print

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
