; Generated by Variable Module - Standalone Compiler
; Source: test_variable_simple.mlp
; Date: Dec  3 2025

global _start

    ; Variable: x (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_x: resq 1  ; 64-bit integer

section .text
    mov rax, 42
    mov [var_x], rax
    ; Variable: y (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_y: resq 1  ; 64-bit integer

section .text
    mov rax, 100
    mov [var_y], rax
    ; Variable: z (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_z: resq 1  ; 64-bit integer

section .text
    mov rax, 0
    mov [var_z], rax

; Program entry point
section .text
_start:
    ; Variables initialized above
    
    ; Exit program
    mov rax, 60        ; sys_exit
    xor rdi, rdi       ; exit code 0
    syscall
