# Module: /home/pardus/projeler/MLP/MLP/compiler/stage1/modules/core/type_mapper.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.text


# Function: type_name_to_kind
.global type_name_to_kind
type_name_to_kind:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: type_name at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_0:
    .string "int"
.text
    leaq .str_cmp_0(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    test %rax, %rax       # Check first result
    jnz .logical_or_true_0  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_1:
    .string "numeric"
.text
    leaq .str_cmp_1(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
.logical_or_true_0:
    # OR result in rax
    test %rax, %rax
    jz .if_end_1
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_INT
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_1:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_2:
    .string "float"
.text
    leaq .str_cmp_2(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_3
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_FLOAT
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_3:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_3:
    .string "string"
.text
    leaq .str_cmp_3(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    test %rax, %rax       # Check first result
    jnz .logical_or_true_1  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_4:
    .string "text"
.text
    leaq .str_cmp_4(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
.logical_or_true_1:
    # OR result in rax
    test %rax, %rax
    jz .if_end_5
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_STRING
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_5:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_5:
    .string "bool"
.text
    leaq .str_cmp_5(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    test %rax, %rax       # Check first result
    jnz .logical_or_true_2  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_6:
    .string "boolean"
.text
    leaq .str_cmp_6(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
.logical_or_true_2:
    # OR result in rax
    test %rax, %rax
    jz .if_end_7
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_BOOL
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_7:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_7:
    .string "void"
.text
    leaq .str_cmp_7(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_9
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_VOID
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_9:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load type_name

.section .rodata
.str_cmp_8:
    .string "char"
.text
    leaq .str_cmp_8(%rip), %r9  # Load string address
    # String comparison (text vs text)
    movq %r8, %rdi  # arg1: first string
    movq %r9, %rsi  # arg2: second string
    call mlp_string_compare  # Returns <0, 0, or >0 (int/32-bit)
    cmpl $0, %eax  # Compare result with 0 (YZ_69: use eax for int)
    sete %al
    movzbl %al, %eax        # Zero-extend al to eax (YZ_69)
    movslq %eax, %rax       # Sign-extend eax to rax
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_11
    # Then body
    movq 0(%rbp), %r8  # Load TYPE_CHAR
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return
.if_end_11:
    movq 0(%rbp), %r8  # Load TYPE_UNKNOWN
    movq %r8, %rax  # Return value
    jmp .Ltype_name_to_kind_return

.Ltype_name_to_kind_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: type_kind_to_name
.global type_kind_to_name
type_kind_to_name:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: kind at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_INT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_13
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_0: .asciz "numeric"
    .section .text
    leaq _str_0(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_13:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_FLOAT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_15
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_1: .asciz "float"
    .section .text
    leaq _str_1(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_15:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_17
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_2: .asciz "string"
    .section .text
    leaq _str_2(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_17:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_BOOL
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_19
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_3: .asciz "boolean"
    .section .text
    leaq _str_3(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_19:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_VOID
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_21
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_4: .asciz "void"
    .section .text
    leaq _str_4(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_21:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_CHAR
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_23
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_5: .asciz "char"
    .section .text
    leaq _str_5(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_23:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_ARRAY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_25
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_6: .asciz "array"
    .section .text
    leaq _str_6(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_25:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_POINTER
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_27
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_7: .asciz "pointer"
    .section .text
    leaq _str_7(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_27:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_FUNCTION
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_29
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_8: .asciz "function"
    .section .text
    leaq _str_8(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_29:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_STRUCT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_31
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_9: .asciz "struct"
    .section .text
    leaq _str_9(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_31:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_ENUM
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_33
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_10: .asciz "enum"
    .section .text
    leaq _str_10(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_33:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_GENERIC
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_35
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_11: .asciz "generic"
    .section .text
    leaq _str_11(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_35:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_UNKNOWN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_37
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_12: .asciz "unknown"
    .section .text
    leaq _str_12(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_37:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_ERROR
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_39
    # Then body

    # Arithmetic expression
    .section .rodata
    _str_13: .asciz "error"
    .section .text
    leaq _str_13(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return
.if_end_39:

    # Arithmetic expression
    .section .rodata
    _str_14: .asciz "unknown"
    .section .text
    leaq _str_14(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltype_kind_to_name_return

.Ltype_kind_to_name_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: types_compatible
.global types_compatible
types_compatible:
    pushq %rbp
    movq %rsp, %rbp
    subq $32, %rsp
    # Parameter: lhs_kind at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Parameter: rhs_kind at -16(%rbp)
    movq %rsi, -16(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load lhs_kind
    movq -16(%rbp), %r9  # Load rhs_kind
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_41
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltypes_compatible_return
.if_end_41:
    # Variable: lhs_is_numeric at -24(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -24(%rbp)  # Initialize lhs_is_numeric

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load lhs_kind
    movq 0(%rbp), %r9  # Load TYPE_INT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    test %rax, %rax       # Check first result
    jnz .logical_or_true_3  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load lhs_kind
    movq 0(%rbp), %r9  # Load TYPE_FLOAT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
.logical_or_true_3:
    # OR result in rax
    test %rax, %rax
    jz .if_end_43
    # Then body
    # Assignment: lhs_is_numeric = ...

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to lhs_is_numeric
.if_end_43:
    # Variable: rhs_is_numeric at -32(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -32(%rbp)  # Initialize rhs_is_numeric

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load rhs_kind
    movq 0(%rbp), %r9  # Load TYPE_INT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    test %rax, %rax       # Check first result
    jnz .logical_or_true_4  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load rhs_kind
    movq 0(%rbp), %r9  # Load TYPE_FLOAT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
.logical_or_true_4:
    # OR result in rax
    test %rax, %rax
    jz .if_end_45
    # Then body
    # Assignment: rhs_is_numeric = ...

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Store to rhs_is_numeric
.if_end_45:

    # If statement

    # Comparison with logical chaining
    movq -24(%rbp), %r8  # Load lhs_is_numeric
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_5  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -32(%rbp), %r8  # Load rhs_is_numeric
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
.logical_and_false_5:
    # AND result in rax
    test %rax, %rax
    jz .if_end_47
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltypes_compatible_return
.if_end_47:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load lhs_kind
    movq 0(%rbp), %r9  # Load TYPE_UNKNOWN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    test %rax, %rax       # Check first result
    jnz .logical_or_true_6  # Skip if true (short-circuit)

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load rhs_kind
    movq 0(%rbp), %r9  # Load TYPE_UNKNOWN
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
.logical_or_true_6:
    # OR result in rax
    test %rax, %rax
    jz .if_end_49
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltypes_compatible_return
.if_end_49:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Ltypes_compatible_return

.Ltypes_compatible_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_primitive_type
.global is_primitive_type
is_primitive_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: kind at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_INT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_51
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return
.if_end_51:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_FLOAT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_53
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return
.if_end_53:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_BOOL
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_55
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return
.if_end_55:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_CHAR
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_57
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return
.if_end_57:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_STRING
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_59
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return
.if_end_59:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_primitive_type_return

.Lis_primitive_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_composite_type
.global is_composite_type
is_composite_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: kind at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_ARRAY
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_61
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_composite_type_return
.if_end_61:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_STRUCT
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_63
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_composite_type_return
.if_end_63:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_ENUM
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_65
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_composite_type_return
.if_end_65:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_composite_type_return

.Lis_composite_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_callable_type
.global is_callable_type
is_callable_type:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: kind at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load kind
    movq 0(%rbp), %r9  # Load TYPE_FUNCTION
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_67
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_callable_type_return
.if_end_67:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_callable_type_return

.Lis_callable_type_return:
    movq %rbp, %rsp
    popq %rbp
    ret
