# Main program: tests/manual/test_nested_struct.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.section .rodata
.div_zero_msg:
    .string "Division by zero is not allowed!"

.text


# Function: main
.global main
main:
    pushq %rbp
    movq %rsp, %rbp
    # Struct instance: Person john (24 bytes)
    subq $32, %rsp  # Allocate john
    # john is at [rbp - 32]
    # Member assignment: john.age = ...

    # Arithmetic expression
    movq $30, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    # Store to [rbp - 32 + 0] = [rbp - 32]
    movq %r8, -32(%rbp)  # Store nested member
    # Member assignment: john.addr.zip = ...

    # Arithmetic expression
    movq $12345, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    # Store to [rbp - 32 + 8] = [rbp - 24]
    movq %r8, -24(%rbp)  # Store nested member
    # Member assignment: john.addr.street_num = ...

    # Arithmetic expression
    movq $100, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    # Store to [rbp - 32 + 16] = [rbp - 16]
    movq %r8, -16(%rbp)  # Store nested member

    # Arithmetic expression
    # Member access: john.addr.zip
    # Load from [rbp - 32 + 8] = [rbp - 24]
    movq -24(%rbp), %r8  # Load nested member value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lmain_return

.Lmain_return:
    movq %rbp, %rsp
    popq %rbp
    ret
