# Generated by MELP Simple Codegen
.text

# Function: count_vars
.globl count_vars
.type count_vars, @function
count_vars:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    movq $1, %rax
    movq $1, %rax
    # Unknown variable: a
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: b
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: ab
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: c
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: total
    movq $0, %rax
    # return expression
    leave
    ret
    # end of count_vars
.size count_vars, .-count_vars

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call count_vars
    # Unknown variable: result
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata

.section .note.GNU-stack,"",@progbits
