# Generated by MELP Simple Codegen
.text

# Function: generate_var_code
.globl generate_var_code
.type generate_var_code, @function
generate_var_code:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    # return expression
    leave
    ret
    # end of generate_var_code
.size generate_var_code, .-generate_var_code

# Function: compile_one_var
.globl compile_one_var
.type compile_one_var, @function
compile_one_var:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call generate_var_code
    # Unknown variable: code
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_one_var
.size compile_one_var, .-compile_one_var

# Function: compile_three_vars
.globl compile_three_vars
.type compile_three_vars, @function
compile_three_vars:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_one_var
    call compile_one_var
    call compile_one_var
    # Unknown variable: a
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: b
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: ab
    movq $0, %rax
    pushq %rax  # save left operand
    # Unknown variable: c
    movq $0, %rax
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    # Unknown variable: total
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_three_vars
.size compile_three_vars, .-compile_three_vars

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    # print("1\n")
    leaq .str0(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str1(%rip), %rdi
    call puts@PLT
    # print("1\n")
    leaq .str2(%rip), %rdi
    call puts@PLT
    call compile_three_vars
    # print("3\n")
    leaq .str3(%rip), %rdi
    call puts@PLT
    # print("0\n")
    leaq .str4(%rip), %rdi
    call puts@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "1\n"
.str1:
    .string "1\n"
.str2:
    .string "1\n"
.str3:
    .string "3\n"
.str4:
    .string "0\n"

.section .note.GNU-stack,"",@progbits
