; Generated by melpc bootstrap compiler
section .data
    msg_ok: db 'MELP Module OK',10,0

section .bss
    sum: resq 1
    diff: resq 1
    product: resq 1
    quotient: resq 1
    remainder: resq 1
    simple: resq 1

section .text
    extern mlp_print
    extern mlp_malloc
    global _start

_start:
    ; sum = 10 + 5
    mov rax, 10
    add rax, 5
    mov qword [sum], rax
    ; diff = 20 - 8
    mov rax, 20
    sub rax, 8
    mov qword [diff], rax
    ; product = 6 * 7
    mov rax, 6
    imul rax, 7
    mov qword [product], rax
    ; quotient = 100 / 5
    mov rax, 100
    xor rdx, rdx
    mov rbx, 5
    idiv rbx
    mov qword [quotient], rax
    ; remainder = 17 % 5
    mov rax, 17
    xor rdx, rdx
    mov rbx, 5
    idiv rbx
    mov rax, rdx
    mov qword [remainder], rax
    ; simple = 42
    mov qword [simple], 42

    ; Print success message
    mov rdi, msg_ok
    call mlp_print

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
