# Module: core/char_utils.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.text


# Function: is_digit
.global is_digit
is_digit:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $48, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_0  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $57, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setle %al
    # Single comparison result in rax
.logical_and_false_0:
    # AND result in rax
    test %rax, %rax
    jz .if_end_1
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_digit_return
.if_end_1:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_digit_return

.Lis_digit_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_alpha
.global is_alpha
is_alpha:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $65, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_1  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $90, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setle %al
    # Single comparison result in rax
.logical_and_false_1:
    # AND result in rax
    test %rax, %rax
    jz .if_end_3
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alpha_return
.if_end_3:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $97, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_2  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $122, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setle %al
    # Single comparison result in rax
.logical_and_false_2:
    # AND result in rax
    test %rax, %rax
    jz .if_end_5
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alpha_return
.if_end_5:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alpha_return

.Lis_alpha_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_alnum
.global is_alnum
is_alnum:
    pushq %rbp
    movq %rsp, %rbp
    subq $24, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Variable: is_alpha_result at -16(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -16(%rbp)  # Initialize is_alpha_result
    # Assignment: is_alpha_result = ...

    # Arithmetic expression
    # Array index access: is_alpha
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to is_alpha_result

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load is_alpha_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_7
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alnum_return
.if_end_7:
    # Variable: is_digit_result at -24(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -24(%rbp)  # Initialize is_digit_result
    # Assignment: is_digit_result = ...

    # Arithmetic expression
    # Array index access: is_digit
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Store to is_digit_result

    # If statement

    # Comparison with logical chaining
    movq -24(%rbp), %r8  # Load is_digit_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_9
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alnum_return
.if_end_9:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_alnum_return

.Lis_alnum_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_space
.global is_space
is_space:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $32, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_11
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_space_return
.if_end_11:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $9, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_13
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_space_return
.if_end_13:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $10, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_15
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_space_return
.if_end_15:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $13, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_17
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_space_return
.if_end_17:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_space_return

.Lis_space_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_upper
.global is_upper
is_upper:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $65, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_3  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $90, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setle %al
    # Single comparison result in rax
.logical_and_false_3:
    # AND result in rax
    test %rax, %rax
    jz .if_end_19
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_upper_return
.if_end_19:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_upper_return

.Lis_upper_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_lower
.global is_lower
is_lower:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $97, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_4  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $122, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setle %al
    # Single comparison result in rax
.logical_and_false_4:
    # AND result in rax
    test %rax, %rax
    jz .if_end_21
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_lower_return
.if_end_21:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_lower_return

.Lis_lower_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: to_upper
.global to_upper
to_upper:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Variable: is_lower_result at -16(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -16(%rbp)  # Initialize is_lower_result
    # Assignment: is_lower_result = ...

    # Arithmetic expression
    # Array index access: is_lower
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to is_lower_result

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load is_lower_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_23
    # Then body

    # Arithmetic expression
    movq -8(%rbp), %r8  # Load c
    movq $32, %r9  # Literal
    subq %r9, %r8
    jo .overflow_detected_0
    jmp .no_overflow_0
.overflow_detected_0:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_sub
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_0:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lto_upper_return
.if_end_23:
    movq -8(%rbp), %r8  # Load c
    movq %r8, %rax  # Return value
    jmp .Lto_upper_return

.Lto_upper_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: to_lower
.global to_lower
to_lower:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Variable: is_upper_result at -16(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -16(%rbp)  # Initialize is_upper_result
    # Assignment: is_upper_result = ...

    # Arithmetic expression
    # Array index access: is_upper
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to is_upper_result

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load is_upper_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_25
    # Then body

    # Arithmetic expression
    movq -8(%rbp), %r8  # Load c
    movq $32, %r9  # Literal
    addq %r9, %r8
    jo .overflow_detected_1
    jmp .no_overflow_1
.overflow_detected_1:
    # Overflow detected - promote to BigDecimal
    pushq %rdi
    pushq %rsi
    movq %r8, %rdi
    call sto_bigdec_from_int64
    movq %rax, %rdi # First BigDecimal
    movq %r9, %rsi
    call sto_bigdec_from_int64
    movq %rax, %rsi # Second BigDecimal
    call sto_bigdec_add
    popq %rsi
    popq %rdi
    movq %rax, %r8 # BigDecimal pointer in result register
.no_overflow_1:
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lto_lower_return
.if_end_25:
    movq -8(%rbp), %r8  # Load c
    movq %r8, %rax  # Return value
    jmp .Lto_lower_return

.Lto_lower_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_identifier_start
.global is_identifier_start
is_identifier_start:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Variable: is_alpha_result at -16(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -16(%rbp)  # Initialize is_alpha_result
    # Assignment: is_alpha_result = ...

    # Arithmetic expression
    # Array index access: is_alpha
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to is_alpha_result

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load is_alpha_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_27
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_start_return
.if_end_27:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $95, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_29
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_start_return
.if_end_29:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_start_return

.Lis_identifier_start_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_identifier_char
.global is_identifier_char
is_identifier_char:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)
    # Variable: is_alnum_result at -16(%rbp)
    movq $0, %r8  # Literal value
    movq %r8, -16(%rbp)  # Initialize is_alnum_result
    # Assignment: is_alnum_result = ...

    # Arithmetic expression
    # Array index access: is_alnum
    movq 0(%rbp), %rbx  # Load array pointer
    movq -8(%rbp), %rcx  # Load index value
    shlq $3, %rcx  # index * 8
    movq (%rbx,%rcx), %rax  # Get element
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Store to is_alnum_result

    # If statement

    # Comparison with logical chaining
    movq -16(%rbp), %r8  # Load is_alnum_result
    movq $1, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_31
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_char_return
.if_end_31:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $95, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_33
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_char_return
.if_end_33:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_identifier_char_return

.Lis_identifier_char_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_ascii
.global is_ascii
is_ascii:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: c at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $0, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setge %al
    test %rax, %rax       # Check first result
    jz .logical_and_false_5  # Skip if false (short-circuit)

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load c
    movq $128, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    setl %al
    # Single comparison result in rax
.logical_and_false_5:
    # AND result in rax
    test %rax, %rax
    jz .if_end_35
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_ascii_return
.if_end_35:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_ascii_return

.Lis_ascii_return:
    movq %rbp, %rsp
    popq %rbp
    ret
