; Generated by melpc bootstrap compiler
section .data
    msg_ok: db 'MELP Module OK',10,0

section .bss
    is_equal: resq 1
    is_not_equal: resq 1
    is_less: resq 1
    is_less_equal: resq 1
    is_greater: resq 1
    is_greater_equal: resq 1

section .text
    extern mlp_print
    extern mlp_malloc
    global _start

_start:
    ; is_equal = 10 == 10
    mov rax, 10
    cmp rax, 10
    sete al
    movzx rax, al
    mov qword [is_equal], rax
    ; is_not_equal = 10 != 5
    mov rax, 10
    cmp rax, 5
    setne al
    movzx rax, al
    mov qword [is_not_equal], rax
    ; is_less = 5 < 10
    mov rax, 5
    cmp rax, 10
    setl al
    movzx rax, al
    mov qword [is_less], rax
    ; is_less_equal = 10 <= 10
    mov rax, 10
    cmp rax, 10
    setle al
    movzx rax, al
    mov qword [is_less_equal], rax
    ; is_greater = 20 > 15
    mov rax, 20
    cmp rax, 15
    setg al
    movzx rax, al
    mov qword [is_greater], rax
    ; is_greater_equal = 15 >= 15
    mov rax, 15
    cmp rax, 15
    setge al
    movzx rax, al
    mov qword [is_greater_equal], rax

    ; Print success message
    mov rdi, msg_ok
    call mlp_print

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
