; Generated by melpc bootstrap compiler
section .data
    msg_ok: db 'MELP Module OK',10,0


section .bss
    x: resq 1
    result: resq 1
    a: resq 1
    b: resq 1
    c: resq 1
    d: resq 1

section .text
    extern mlp_print
    extern mlp_malloc
    global _start

_start:
    ; x = 10
    mov qword [x], 10
    ; result = 0
    mov qword [result], 0

    ; if statement
    mov rax, qword [x]
    cmp rax, 5
    jle .endif_0
.then_0:
    mov qword [result], 100
.endif_0:
    ; result = 100
    mov qword [result], 100
    ; a = 3
    mov qword [a], 3
    ; b = 0
    mov qword [b], 0

    ; if statement
    mov rax, qword [a]
    cmp rax, 5
    jge .else_1
.then_1:
    mov qword [b], 1
    jmp .endif_1
.else_1:
    mov qword [b], 2
.endif_1:
    ; b = 1
    mov qword [b], 1
    ; b = 2
    mov qword [b], 2
    ; c = 42
    mov qword [c], 42
    ; d = 0
    mov qword [d], 0

    ; if statement
    mov rax, qword [c]
    cmp rax, 42
    jne .endif_2
.then_2:
    mov qword [d], 99
.endif_2:
    ; d = 99
    mov qword [d], 99

    ; Print success message
    mov rdi, msg_ok
    call mlp_print

    ; Exit
    mov rax, 60
    xor rdi, rdi
    syscall
