; Generated by MELP Stage 0 Compiler
global _start

    ; Variable: x (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_x: resq 1  ; 64-bit integer

section .text
    mov rax, 5
    mov [var_x], rax
    ; Variable: y (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_y: resq 1  ; 64-bit integer

section .text
    mov rax, 10
    mov [var_y], rax
    ; Variable: sum (type: numeric)
    ; TTO: INT64 optimization

section .bss
    var_sum: resq 1  ; 64-bit integer

section .text
    mov rax, 15
    mov [var_sum], rax

section .text
_start:
    ; Exit program
    mov rax, 60     ; sys_exit
    xor rdi, rdi    ; status 0
    syscall
