# Generated by MELP Simple Codegen
.text

# Function: is_digit
.globl is_digit
.type is_digit, @function
is_digit:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param c
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $48, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setl %al  # <
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse0  # if false, jump to else
    movq $0, %rax
    # return expression
    leave
    ret
    jmp .Lend1  # skip else
.Lelse0:
.Lend1:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $57, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setg %al  # >
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse2  # if false, jump to else
    movq $0, %rax
    # return expression
    leave
    ret
    jmp .Lend3  # skip else
.Lelse2:
.Lend3:
    movq $1, %rax
    # return expression
    leave
    ret
    # end of is_digit
.size is_digit, .-is_digit

# Function: is_alpha
.globl is_alpha
.type is_alpha, @function
is_alpha:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param c
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load c
    pushq %rax  # save left
    movq $65, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax  # compare
    setge %al  # >=
    movzbq %al, %rax  # zero extend
    testq %rax, %rax
    jz .Lelse4  # if false, jump to else
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $90, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setle %al  # <=
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse6  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend7  # skip else
.Lelse6:
.Lend7:
    jmp .Lend5  # skip else
.Lelse4:
.Lend5:
    movq -8(%rbp), %rax  # load c
    pushq %rax  # save left
    movq $97, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax  # compare
    setge %al  # >=
    movzbq %al, %rax  # zero extend
    testq %rax, %rax
    jz .Lelse8  # if false, jump to else
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $122, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    setle %al  # <=
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse10  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend11  # skip else
.Lelse10:
.Lend11:
    jmp .Lend9  # skip else
.Lelse8:
.Lend9:
    movq $0, %rax
    # return expression
    leave
    ret
    # end of is_alpha
.size is_alpha, .-is_alpha

# Function: is_space
.globl is_space
.type is_space, @function
is_space:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param c
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $32, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse12  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend13  # skip else
.Lelse12:
.Lend13:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $9, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse14  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend15  # skip else
.Lelse14:
.Lend15:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $10, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse16  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend17  # skip else
.Lelse16:
.Lend17:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $13, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse18  # if false, jump to else
    movq $1, %rax
    # return expression
    leave
    ret
    jmp .Lend19  # skip else
.Lelse18:
.Lend19:
    movq $0, %rax
    # return expression
    leave
    ret
    # end of is_space
.size is_space, .-is_space

# Function: get_token
.globl get_token
.type get_token, @function
get_token:
    pushq %rbp
    movq %rsp, %rbp
    movq %rdi, -8(%rbp)  # param c
    subq $128, %rsp  # allocate stack for locals
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $0, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse20  # if false, jump to else
    movq $0, %rax
    # return expression
    leave
    ret
    jmp .Lend21  # skip else
.Lelse20:
.Lend21:
    movq -8(%rbp), %rax  # load c
    movq %rax, %rdi  # arg 0
    call is_digit
    testq %rax, %rax
    jz .Lelse22  # if false, jump to else
    movq $3, %rax
    # return expression
    leave
    ret
    jmp .Lend23  # skip else
.Lelse22:
.Lend23:
    movq -8(%rbp), %rax  # load c
    movq %rax, %rdi  # arg 0
    call is_alpha
    testq %rax, %rax
    jz .Lelse24  # if false, jump to else
    movq $2, %rax
    # return expression
    leave
    ret
    jmp .Lend25  # skip else
.Lelse24:
.Lend25:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $61, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse26  # if false, jump to else
    movq $4, %rax
    # return expression
    leave
    ret
    jmp .Lend27  # skip else
.Lelse26:
.Lend27:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $59, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse28  # if false, jump to else
    movq $5, %rax
    # return expression
    leave
    ret
    jmp .Lend29  # skip else
.Lelse28:
.Lend29:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $43, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse30  # if false, jump to else
    movq $6, %rax
    # return expression
    leave
    ret
    jmp .Lend31  # skip else
.Lelse30:
.Lend31:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $45, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse32  # if false, jump to else
    movq $7, %rax
    # return expression
    leave
    ret
    jmp .Lend33  # skip else
.Lelse32:
.Lend33:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $42, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse34  # if false, jump to else
    movq $8, %rax
    # return expression
    leave
    ret
    jmp .Lend35  # skip else
.Lelse34:
.Lend35:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $47, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse36  # if false, jump to else
    movq $9, %rax
    # return expression
    leave
    ret
    jmp .Lend37  # skip else
.Lelse36:
.Lend37:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $40, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse38  # if false, jump to else
    movq $10, %rax
    # return expression
    leave
    ret
    jmp .Lend39  # skip else
.Lelse38:
.Lend39:
    movq -8(%rbp), %rax  # load c
    pushq %rax
    movq $41, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax
    sete %al  # ==
    movzbq %al, %rax
    testq %rax, %rax
    jz .Lelse40  # if false, jump to else
    movq $11, %rax
    # return expression
    leave
    ret
    jmp .Lend41  # skip else
.Lelse40:
.Lend41:
    movq $0, %rax
    # return expression
    leave
    ret
    # end of get_token
.size get_token, .-get_token

# Function: compile_mvl
.globl compile_mvl
.type compile_mvl, @function
compile_mvl:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store token1
    movq $0, %rax
    movq %rax, -16(%rbp)  # store token2
    movq $0, %rax
    movq %rax, -24(%rbp)  # store token3
    movq $65, %rax
    movq %rax, %rdi  # arg 0
    call get_token
    movq %rax, -8(%rbp)  # update token1
    movq $53, %rax
    movq %rax, %rdi  # arg 0
    call get_token
    movq %rax, -16(%rbp)  # update token2
    movq $43, %rax
    movq %rax, %rdi  # arg 0
    call get_token
    movq %rax, -24(%rbp)  # update token3
    movq -8(%rbp), %rax  # load token1
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -16(%rbp), %rax  # load token2
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq -24(%rbp), %rax  # load token3
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str2(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of compile_mvl
.size compile_mvl, .-compile_mvl

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_mvl
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"
.str1:
    .string "%ld\n"
.str2:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
