# Generated by MELP Simple Codegen
.text

# Function: compile_mvl
.globl compile_mvl
.type compile_mvl, @function
compile_mvl:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $1, %rax
    movq %rax, -8(%rbp)  # store status
    movq -8(%rbp), %rax  # load status
    # return expression
    leave
    ret
    # end of compile_mvl
.size compile_mvl, .-compile_mvl

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    call compile_mvl
    movq %rax, -8(%rbp)  # store result
    movq -8(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
