# Generated by MELP Simple Codegen
.text

# Function: test_is_digit
.globl test_is_digit
.type test_is_digit, @function
test_is_digit:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store result
    movq $65, %rax
    pushq %rax  # save left
    movq $48, %rax
    movq %rax, %rbx
    popq %rax
    cmpq %rbx, %rax  # compare
    setge %al  # >=
    movzbq %al, %rax  # zero extend
    movq %rax, -8(%rbp)  # update result
    movq -8(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of test_is_digit
.size test_is_digit, .-test_is_digit

# Function: test_is_alpha
.globl test_is_alpha
.type test_is_alpha, @function
test_is_alpha:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    movq %rax, -8(%rbp)  # store result
    movq %rax, -8(%rbp)  # update result
    movq -8(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str1(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of test_is_alpha
.size test_is_alpha, .-test_is_alpha

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"
.str1:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
