# Generated by MELP Simple Codegen
.text

# Function: main
.globl main
.type main, @function
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $128, %rsp  # allocate stack for locals
    movq $5, %rax
    movq %rax, -8(%rbp)  # store x
    movq $3, %rax
    movq %rax, -16(%rbp)  # store y
    movq -8(%rbp), %rax  # load x
    pushq %rax  # save left operand
    movq -16(%rbp), %rax  # load y
    movq %rax, %rbx  # right operand in rbx
    popq %rax  # restore left operand
    addq %rbx, %rax
    movq %rax, -24(%rbp)  # store result
    movq -24(%rbp), %rax  # load result
    # print_int(...)
    movq %rax, %rsi  # value to print
    leaq .str0(%rip), %rdi
    xorq %rax, %rax  # no floating point
    call printf@PLT
    movq $0, %rax
    # return expression
    leave
    ret
    # end of main
.size main, .-main

.section .rodata
.str0:
    .string "%ld\n"

.section .note.GNU-stack,"",@progbits
