; Generated by MLP Smart Pointers System
; NASM x86-64 assembly

section .data

section .bss
    node_ptr: resq 1    ; Rc<Node>
    shared_data: resq 1    ; Arc<Data>
    boxed_value: resq 1    ; Box<i32>
    weak_ref: resq 1    ; Weak<Node>

section .text
    global _start
    extern malloc, free

_start:

    ; Rc::clone() - increment strong_count
    mov rax, [node_ptr]    ; Load inner pointer
    test rax, rax
    jz rc_clone_skip_0    ; Skip if NULL
    inc qword [rax]    ; strong_count++
rc_clone_skip_0:

    ; Unknown operation

    ; Rc::drop() - decrement strong_count
    mov rax, [node_ptr]    ; Load inner pointer
    test rax, rax
    jz rc_drop_skip_1    ; Skip if NULL
    dec qword [rax]    ; strong_count--
    cmp qword [rax], 0
    je rc_drop_free_data_2    ; Free data if last strong ref
    jmp rc_drop_skip_1
rc_drop_free_data_2:
    mov rdi, [rax + 16]    ; Load data pointer
    call free    ; Free data
    mov rax, [node_ptr]    ; Reload inner pointer
    cmp qword [rax + 8], 0    ; Check weak_count
    je rc_drop_free_inner_3    ; Free inner if no weak refs
    jmp rc_drop_skip_1
rc_drop_free_inner_3:
    mov rdi, rax    ; inner pointer
    call free    ; Free inner
rc_drop_skip_1:

    ; Arc::clone() - atomic increment strong_count
    mov rax, [shared_data]    ; Load inner pointer
    test rax, rax
    jz arc_clone_skip_4    ; Skip if NULL
    lock inc qword [rax]    ; Atomic strong_count++
arc_clone_skip_4:

    ; Arc::drop() - atomic decrement strong_count
    mov rax, [shared_data]    ; Load inner pointer
    test rax, rax
    jz arc_drop_skip_5    ; Skip if NULL
    mov rbx, rax    ; Save inner pointer
    mov rcx, 1
    lock xadd [rax], rcx    ; Atomic fetch_sub
    cmp rcx, 1
    je arc_drop_free_data_6    ; Free data if last strong ref
    jmp arc_drop_skip_5
arc_drop_free_data_6:
    mov rdi, [rbx + 16]    ; Load data pointer
    call free    ; Free data
    mov rcx, [rbx + 8]    ; Atomic load weak_count
    test rcx, rcx
    jz arc_drop_free_inner_7    ; Free inner if no weak refs
    jmp arc_drop_skip_5
arc_drop_free_inner_7:
    mov rdi, rbx    ; inner pointer
    call free    ; Free inner
arc_drop_skip_5:

    ; Box::drop() - free heap memory
    mov rax, [boxed_value]    ; Load box pointer
    test rax, rax
    jz box_drop_skip_8    ; Skip if NULL
    mov rdi, [rax]    ; Load data pointer
    call free    ; Free data
    mov rdi, [boxed_value]    ; Reload box pointer
    call free    ; Free box
box_drop_skip_8:

    ; Exit program
    mov rax, 60    ; sys_exit
    xor rdi, rdi    ; exit code 0
    syscall
