# Main program: modules/parser_mlp/parser_expr.mlp
# Generated by MELP Compiler (YZ_44 Part 5.1)

.section .rodata
.div_zero_msg:
    .string "Division by zero is not allowed!"

.text


# Function: get_operator_precedence
.global get_operator_precedence
get_operator_precedence:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: token_type at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $18, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_1
    # Then body

    # Arithmetic expression
    movq $6, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_1:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $19, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_3
    # Then body

    # Arithmetic expression
    movq $6, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_3:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $20, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_5
    # Then body

    # Arithmetic expression
    movq $6, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_5:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $16, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_7
    # Then body

    # Arithmetic expression
    movq $5, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_7:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $17, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_9
    # Then body

    # Arithmetic expression
    movq $5, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_9:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $25, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_11
    # Then body

    # Arithmetic expression
    movq $4, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_11:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $26, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_13
    # Then body

    # Arithmetic expression
    movq $4, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_13:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $27, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_15
    # Then body

    # Arithmetic expression
    movq $4, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_15:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $28, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_17
    # Then body

    # Arithmetic expression
    movq $4, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_17:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $23, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_19
    # Then body

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_19:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $24, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_21
    # Then body

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_21:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $29, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_23
    # Then body

    # Arithmetic expression
    movq $2, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_23:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load token_type
    movq $30, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_25
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return
.if_end_25:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lget_operator_precedence_return

.Lget_operator_precedence_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: is_binary_op
.global is_binary_op
is_binary_op:
    pushq %rbp
    movq %rsp, %rbp
    subq $8, %rsp
    # Parameter: t at -8(%rbp)
    movq %rdi, -8(%rbp)

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $16, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_27
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_27:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $17, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_29
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_29:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $18, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_31
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_31:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $19, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_33
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_33:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $20, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_35
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_35:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $23, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_37
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_37:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $24, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_39
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_39:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $25, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_41
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_41:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $26, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_43
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_43:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $27, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_45
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_45:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $28, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_47
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_47:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $29, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_49
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_49:

    # If statement

    # Comparison with logical chaining
    movq -8(%rbp), %r8  # Load t
    movq $30, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_51
    # Then body

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return
.if_end_51:

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lis_binary_op_return

.Lis_binary_op_return:
    movq %rbp, %rsp
    popq %rbp
    ret

# Function: main
.global main
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $512, %rsp
    # MLP Print Module - Generated Assembly
    # Target: x86-64 Linux
    # STO Support: BigDecimal, SSO String

    # STO Runtime Functions: sto_print_int64, printf, free

    .section .rodata
str_0:
    .asciz "=== Expression Parser Tests ===\n"  # string with newline
    .set str_0_len, . - str_0 - 2  # length without null and newline

    .text
    # Print: === Expression Parser Tests ===
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_0(%rip), %rsi   # string address (RIP-relative)
    movq $str_0_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_0: .asciz ""
    .section .text
    leaq _str_0(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_1: .asciz "Test 1: Number literal (42)"
    .section .text
    leaq _str_1(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: tok1 at -8(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_2: .asciz "42"
    .section .text
    leaq _str_2(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -8(%rbp)  # Initialize tok1
    # Variable: tokens at -16(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 1 elements, type=0
    # Allocate array on heap
    movq $1, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -8(%rbp), %r8  # Load tok1
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -16(%rbp)  # Initialize tokens
    # Variable: t at -24(%rbp)

    # Arithmetic expression
    # Array index access: tokens
    movq -16(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -24(%rbp)  # Initialize t
    # Variable: ttype at -32(%rbp)

    # Arithmetic expression
    # Array index access: t
    movq -24(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -32(%rbp)  # Initialize ttype
    # Variable: tval at -40(%rbp)

    # Arithmetic expression
    # Array index access: t
    movq -24(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -40(%rbp)  # Initialize tval

    # If statement

    # Comparison with logical chaining
    movq -32(%rbp), %r8  # Load ttype
    movq $12, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_53
    # Then body
    .section .rodata
str_1:
    .asciz "  AST: LITERAL_NUM(\n"  # string with newline
    .set str_1_len, . - str_1 - 2  # length without null and newline

    .text
    # Print:   AST: LITERAL_NUM(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_1(%rip), %rsi   # string address (RIP-relative)
    movq $str_1_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -40(%rbp), %r8  # Load tval
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_3:
    .asciz ")\n"  # string with newline
    .set str_3_len, . - str_3 - 2  # length without null and newline

    .text
    # Print: )
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_3(%rip), %rsi   # string address (RIP-relative)
    movq $str_3_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_3: .asciz ""
    .section .text
    leaq _str_3(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_53:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_4: .asciz ""
    .section .text
    leaq _str_4(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_5: .asciz "Test 2: Binary (2 + 3)"
    .section .text
    leaq _str_5(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t2a at -48(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_6: .asciz "2"
    .section .text
    leaq _str_6(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -48(%rbp)  # Initialize t2a
    # Variable: t2b at -56(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $16, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_7: .asciz "+"
    .section .text
    leaq _str_7(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -56(%rbp)  # Initialize t2b
    # Variable: t2c at -64(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_8: .asciz "3"
    .section .text
    leaq _str_8(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $5, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -64(%rbp)  # Initialize t2c
    # Variable: toks2 at -72(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 3 elements, type=0
    # Allocate array on heap
    movq $3, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -48(%rbp), %r8  # Load t2a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -56(%rbp), %r8  # Load t2b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -64(%rbp), %r8  # Load t2c
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -72(%rbp)  # Initialize toks2
    # Variable: left at -80(%rbp)

    # Arithmetic expression
    # Array index access: toks2
    movq -72(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -80(%rbp)  # Initialize left
    # Variable: lval at -88(%rbp)

    # Arithmetic expression
    # Array index access: left
    movq -80(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -88(%rbp)  # Initialize lval
    # Variable: op at -96(%rbp)

    # Arithmetic expression
    # Array index access: toks2
    movq -72(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -96(%rbp)  # Initialize op
    # Variable: optype at -104(%rbp)

    # Arithmetic expression
    # Array index access: op
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -104(%rbp)  # Initialize optype
    # Variable: opval at -112(%rbp)

    # Arithmetic expression
    # Array index access: op
    movq -96(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -112(%rbp)  # Initialize opval
    # Variable: right at -120(%rbp)

    # Arithmetic expression
    # Array index access: toks2
    movq -72(%rbp), %rbx  # Load array pointer from stack
    movq 16(%rbx), %rax  # Get element at index 2
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -120(%rbp)  # Initialize right
    # Variable: rval at -128(%rbp)

    # Arithmetic expression
    # Array index access: right
    movq -120(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -128(%rbp)  # Initialize rval
    .section .rodata
str_4:
    .asciz "  AST: LITERAL_NUM(\n"  # string with newline
    .set str_4_len, . - str_4 - 2  # length without null and newline

    .text
    # Print:   AST: LITERAL_NUM(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_4(%rip), %rsi   # string address (RIP-relative)
    movq $str_4_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -88(%rbp), %r8  # Load lval
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_6:
    .asciz ") \n"  # string with newline
    .set str_6_len, . - str_6 - 2  # length without null and newline

    .text
    # Print: ) 
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_6(%rip), %rsi   # string address (RIP-relative)
    movq $str_6_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -112(%rbp), %r8  # Load opval
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_8:
    .asciz " LITERAL_NUM(\n"  # string with newline
    .set str_8_len, . - str_8 - 2  # length without null and newline

    .text
    # Print:  LITERAL_NUM(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_8(%rip), %rsi   # string address (RIP-relative)
    movq $str_8_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -128(%rbp), %r8  # Load rval
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_10:
    .asciz ")\n"  # string with newline
    .set str_10_len, . - str_10 - 2  # length without null and newline

    .text
    # Print: )
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_10(%rip), %rsi   # string address (RIP-relative)
    movq $str_10_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_9: .asciz ""
    .section .text
    leaq _str_9(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_10: .asciz ""
    .section .text
    leaq _str_10(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_11: .asciz "Test 3: Precedence (2 + 3 * 4)"
    .section .text
    leaq _str_11(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t3a at -136(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_12: .asciz "2"
    .section .text
    leaq _str_12(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -136(%rbp)  # Initialize t3a
    # Variable: t3b at -144(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $16, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_13: .asciz "+"
    .section .text
    leaq _str_13(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -144(%rbp)  # Initialize t3b
    # Variable: t3c at -152(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_14: .asciz "3"
    .section .text
    leaq _str_14(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $5, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -152(%rbp)  # Initialize t3c
    # Variable: t3d at -160(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $18, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_15: .asciz "*"
    .section .text
    leaq _str_15(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $7, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -160(%rbp)  # Initialize t3d
    # Variable: t3e at -168(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_16: .asciz "4"
    .section .text
    leaq _str_16(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $9, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -168(%rbp)  # Initialize t3e
    # Variable: toks3 at -176(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 5 elements, type=0
    # Allocate array on heap
    movq $5, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -136(%rbp), %r8  # Load t3a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -144(%rbp), %r8  # Load t3b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -152(%rbp), %r8  # Load t3c
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq -160(%rbp), %r8  # Load t3d
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    # Element 4
    pushq %rbx

    # Arithmetic expression
    movq -168(%rbp), %r8  # Load t3e
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 32(%rbx)  # Store element at index 4
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -176(%rbp)  # Initialize toks3
    # Variable: op1 at -184(%rbp)

    # Arithmetic expression
    # Array index access: toks3
    movq -176(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -184(%rbp)  # Initialize op1
    # Variable: op1type at -192(%rbp)

    # Arithmetic expression
    # Array index access: op1
    movq -184(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -192(%rbp)  # Initialize op1type
    # Variable: op1prec at -200(%rbp)

    # Arithmetic expression
    # Function call: get_operator_precedence()
    movq -192(%rbp), %r10  # Load op1type
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call get_operator_precedence
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -200(%rbp)  # Initialize op1prec
    # Variable: op2 at -208(%rbp)

    # Arithmetic expression
    # Array index access: toks3
    movq -176(%rbp), %rbx  # Load array pointer from stack
    movq 24(%rbx), %rax  # Get element at index 3
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -208(%rbp)  # Initialize op2
    # Variable: op2type at -216(%rbp)

    # Arithmetic expression
    # Array index access: op2
    movq -208(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -216(%rbp)  # Initialize op2type
    # Variable: op2prec at -224(%rbp)

    # Arithmetic expression
    # Function call: get_operator_precedence()
    movq -216(%rbp), %r10  # Load op2type
    pushq %r10  # Save arg 1
    popq %rdi  # Restore arg 1
    call get_operator_precedence
    movq %rax, %r8  # Function return value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -224(%rbp)  # Initialize op2prec

    # If statement

    # Comparison with logical chaining
    movq -224(%rbp), %r8  # Load op2prec
    movq -200(%rbp), %r9  # Load op1prec
    cmpq %r9, %r8
    movq $0, %rax
    setg %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_55
    # Then body

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_17: .asciz "  * has higher precedence (6) than + (5)"
    .section .text
    leaq _str_17(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    .section .rodata
str_11:
    .asciz "  AST: LITERAL_NUM(2) + (LITERAL_NUM(3) * LITERAL_NUM(4))\n"  # string with newline
    .set str_11_len, . - str_11 - 2  # length without null and newline

    .text
    # Print:   AST: LITERAL_NUM(2) + (LITERAL_NUM(3) * LITERAL_NUM(4))
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_11(%rip), %rsi   # string address (RIP-relative)
    movq $str_11_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_18: .asciz ""
    .section .text
    leaq _str_18(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_55:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_19: .asciz ""
    .section .text
    leaq _str_19(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_20: .asciz "Test 4: Variable (x)"
    .section .text
    leaq _str_20(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t4 at -232(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $10, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_21: .asciz "x"
    .section .text
    leaq _str_21(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -232(%rbp)  # Initialize t4
    # Variable: toks4 at -240(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 1 elements, type=0
    # Allocate array on heap
    movq $1, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -232(%rbp), %r8  # Load t4
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -240(%rbp)  # Initialize toks4
    # Variable: var_tok at -248(%rbp)

    # Arithmetic expression
    # Array index access: toks4
    movq -240(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -248(%rbp)  # Initialize var_tok
    # Variable: var_type at -256(%rbp)

    # Arithmetic expression
    # Array index access: var_tok
    movq -248(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -256(%rbp)  # Initialize var_type
    # Variable: var_name at -264(%rbp)

    # Arithmetic expression
    # Array index access: var_tok
    movq -248(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -264(%rbp)  # Initialize var_name

    # If statement

    # Comparison with logical chaining
    movq -256(%rbp), %r8  # Load var_type
    movq $10, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_57
    # Then body
    .section .rodata
str_12:
    .asciz "  AST: VAR(\n"  # string with newline
    .set str_12_len, . - str_12 - 2  # length without null and newline

    .text
    # Print:   AST: VAR(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_12(%rip), %rsi   # string address (RIP-relative)
    movq $str_12_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -264(%rbp), %r8  # Load var_name
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_14:
    .asciz ")\n"  # string with newline
    .set str_14_len, . - str_14 - 2  # length without null and newline

    .text
    # Print: )
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_14(%rip), %rsi   # string address (RIP-relative)
    movq $str_14_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_22: .asciz ""
    .section .text
    leaq _str_22(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_57:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_23: .asciz ""
    .section .text
    leaq _str_23(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_24: .asciz "Test 5: Unary minus (-42)"
    .section .text
    leaq _str_24(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t5a at -272(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $17, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_25: .asciz "-"
    .section .text
    leaq _str_25(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -272(%rbp)  # Initialize t5a
    # Variable: t5b at -280(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_26: .asciz "42"
    .section .text
    leaq _str_26(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $2, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -280(%rbp)  # Initialize t5b
    # Variable: toks5 at -288(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 2 elements, type=0
    # Allocate array on heap
    movq $2, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -272(%rbp), %r8  # Load t5a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -280(%rbp), %r8  # Load t5b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -288(%rbp)  # Initialize toks5
    # Variable: unary_op at -296(%rbp)

    # Arithmetic expression
    # Array index access: toks5
    movq -288(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -296(%rbp)  # Initialize unary_op
    # Variable: unary_type at -304(%rbp)

    # Arithmetic expression
    # Array index access: unary_op
    movq -296(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -304(%rbp)  # Initialize unary_type

    # If statement

    # Comparison with logical chaining
    movq -304(%rbp), %r8  # Load unary_type
    movq $17, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_59
    # Then body
    # Variable: unary_arg at -312(%rbp)

    # Arithmetic expression
    # Array index access: toks5
    movq -288(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -312(%rbp)  # Initialize unary_arg
    # Variable: unary_val at -320(%rbp)

    # Arithmetic expression
    # Array index access: unary_arg
    movq -312(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -320(%rbp)  # Initialize unary_val
    .section .rodata
str_15:
    .asciz "  AST: UNARY(-,LITERAL_NUM(\n"  # string with newline
    .set str_15_len, . - str_15 - 2  # length without null and newline

    .text
    # Print:   AST: UNARY(-,LITERAL_NUM(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_15(%rip), %rsi   # string address (RIP-relative)
    movq $str_15_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    movq -320(%rbp), %r8  # Load unary_val
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rdi  # String pointer as argument
    call puts
    .section .rodata
str_17:
    .asciz "))\n"  # string with newline
    .set str_17_len, . - str_17 - 2  # length without null and newline

    .text
    # Print: ))
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_17(%rip), %rsi   # string address (RIP-relative)
    movq $str_17_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_27: .asciz ""
    .section .text
    leaq _str_27(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_59:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_28: .asciz ""
    .section .text
    leaq _str_28(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_29: .asciz "Test 6: Parentheses ((2 + 3) * 4)"
    .section .text
    leaq _str_29(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t6a at -328(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $73, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_30: .asciz "("
    .section .text
    leaq _str_30(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -328(%rbp)  # Initialize t6a
    # Variable: t6b at -336(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_31: .asciz "2"
    .section .text
    leaq _str_31(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $2, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -336(%rbp)  # Initialize t6b
    # Variable: t6c at -344(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $16, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_32: .asciz "+"
    .section .text
    leaq _str_32(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $4, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -344(%rbp)  # Initialize t6c
    # Variable: t6d at -352(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_33: .asciz "3"
    .section .text
    leaq _str_33(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $6, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -352(%rbp)  # Initialize t6d
    # Variable: t6e at -360(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $74, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_34: .asciz ")"
    .section .text
    leaq _str_34(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $7, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -360(%rbp)  # Initialize t6e
    # Variable: t6f at -368(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $18, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_35: .asciz "*"
    .section .text
    leaq _str_35(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $9, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -368(%rbp)  # Initialize t6f
    # Variable: t6g at -376(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $12, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_36: .asciz "4"
    .section .text
    leaq _str_36(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $11, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -376(%rbp)  # Initialize t6g
    # Variable: toks6 at -384(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 7 elements, type=0
    # Allocate array on heap
    movq $7, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -328(%rbp), %r8  # Load t6a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -336(%rbp), %r8  # Load t6b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -344(%rbp), %r8  # Load t6c
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq -352(%rbp), %r8  # Load t6d
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    # Element 4
    pushq %rbx

    # Arithmetic expression
    movq -360(%rbp), %r8  # Load t6e
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 32(%rbx)  # Store element at index 4
    # Element 5
    pushq %rbx

    # Arithmetic expression
    movq -368(%rbp), %r8  # Load t6f
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 40(%rbx)  # Store element at index 5
    # Element 6
    pushq %rbx

    # Arithmetic expression
    movq -376(%rbp), %r8  # Load t6g
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 48(%rbx)  # Store element at index 6
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -384(%rbp)  # Initialize toks6
    # Variable: paren at -392(%rbp)

    # Arithmetic expression
    # Array index access: toks6
    movq -384(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -392(%rbp)  # Initialize paren
    # Variable: paren_type at -400(%rbp)

    # Arithmetic expression
    # Array index access: paren
    movq -392(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -400(%rbp)  # Initialize paren_type

    # If statement

    # Comparison with logical chaining
    movq -400(%rbp), %r8  # Load paren_type
    movq $73, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_61
    # Then body
    .section .rodata
str_18:
    .asciz "  AST: (LITERAL_NUM(2) + LITERAL_NUM(3)) * LITERAL_NUM(4)\n"  # string with newline
    .set str_18_len, . - str_18 - 2  # length without null and newline

    .text
    # Print:   AST: (LITERAL_NUM(2) + LITERAL_NUM(3)) * LITERAL_NUM(4)
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_18(%rip), %rsi   # string address (RIP-relative)
    movq $str_18_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_37: .asciz ""
    .section .text
    leaq _str_37(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_61:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_38: .asciz ""
    .section .text
    leaq _str_38(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_39: .asciz "Test 7: Comparison (a < b)"
    .section .text
    leaq _str_39(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t7a at -408(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $10, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_40: .asciz "a"
    .section .text
    leaq _str_40(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -408(%rbp)  # Initialize t7a
    # Variable: t7b at -416(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $25, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_41: .asciz "<"
    .section .text
    leaq _str_41(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -416(%rbp)  # Initialize t7b
    # Variable: t7c at -424(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $10, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_42: .asciz "b"
    .section .text
    leaq _str_42(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $5, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -424(%rbp)  # Initialize t7c
    # Variable: toks7 at -432(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 3 elements, type=0
    # Allocate array on heap
    movq $3, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -408(%rbp), %r8  # Load t7a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -416(%rbp), %r8  # Load t7b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -424(%rbp), %r8  # Load t7c
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -432(%rbp)  # Initialize toks7
    # Variable: cmp_left at -440(%rbp)

    # Arithmetic expression
    # Array index access: toks7
    movq -432(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -440(%rbp)  # Initialize cmp_left
    # Variable: cmp_op at -448(%rbp)

    # Arithmetic expression
    # Array index access: toks7
    movq -432(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -448(%rbp)  # Initialize cmp_op
    # Variable: cmp_right at -456(%rbp)

    # Arithmetic expression
    # Array index access: toks7
    movq -432(%rbp), %rbx  # Load array pointer from stack
    movq 16(%rbx), %rax  # Get element at index 2
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -456(%rbp)  # Initialize cmp_right
    # Variable: cmp_type at -464(%rbp)

    # Arithmetic expression
    # Array index access: cmp_op
    movq -448(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -464(%rbp)  # Initialize cmp_type

    # If statement

    # Comparison with logical chaining
    movq -464(%rbp), %r8  # Load cmp_type
    movq $25, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_63
    # Then body
    .section .rodata
str_19:
    .asciz "  AST: VAR(\n"  # string with newline
    .set str_19_len, . - str_19 - 2  # length without null and newline

    .text
    # Print:   AST: VAR(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_19(%rip), %rsi   # string address (RIP-relative)
    movq $str_19_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    # Array index access: cmp_left
    movq -440(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    mov %r8, %rdi  # Move result to first argument (AT&T syntax)
    call sto_print_int64
    .section .rodata
str_21:
    .asciz ") < VAR(\n"  # string with newline
    .set str_21_len, . - str_21 - 2  # length without null and newline

    .text
    # Print: ) < VAR(
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_21(%rip), %rsi   # string address (RIP-relative)
    movq $str_21_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Print expression

    # Arithmetic expression
    # Array index access: cmp_right
    movq -456(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    mov %r8, %rdi  # Move result to first argument (AT&T syntax)
    call sto_print_int64
    .section .rodata
str_23:
    .asciz ")\n"  # string with newline
    .set str_23_len, . - str_23 - 2  # length without null and newline

    .text
    # Print: )
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_23(%rip), %rsi   # string address (RIP-relative)
    movq $str_23_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_43: .asciz ""
    .section .text
    leaq _str_43(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_63:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_44: .asciz ""
    .section .text
    leaq _str_44(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_45: .asciz "Test 8: Logical (a and b)"
    .section .text
    leaq _str_45(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
    # Variable: t8a at -472(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $10, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_46: .asciz "a"
    .section .text
    leaq _str_46(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -472(%rbp)  # Initialize t8a
    # Variable: t8b at -480(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $29, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_47: .asciz "and"
    .section .text
    leaq _str_47(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $3, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -480(%rbp)  # Initialize t8b
    # Variable: t8c at -488(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 4 elements, type=0
    # Allocate array on heap
    movq $4, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq $10, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    .section .rodata
    _str_48: .asciz "b"
    .section .text
    leaq _str_48(%rip), %r8  # Load string pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq $1, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    # Element 3
    pushq %rbx

    # Arithmetic expression
    movq $7, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 24(%rbx)  # Store element at index 3
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -488(%rbp)  # Initialize t8c
    # Variable: toks8 at -496(%rbp)

    # Arithmetic expression
    # Collection literal
    # Array literal: 3 elements, type=0
    # Allocate array on heap
    movq $3, %rdi  # Number of elements
    movq $8, %rsi   # Element size (8 bytes)
    call sto_array_alloc  # Returns pointer in rax
    movq %rax, %rbx  # Save array pointer in rbx
    # Initialize array elements
    # Element 0
    pushq %rbx

    # Arithmetic expression
    movq -472(%rbp), %r8  # Load t8a
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 0(%rbx)  # Store element at index 0
    # Element 1
    pushq %rbx

    # Arithmetic expression
    movq -480(%rbp), %r8  # Load t8b
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 8(%rbx)  # Store element at index 1
    # Element 2
    pushq %rbx

    # Arithmetic expression
    movq -488(%rbp), %r8  # Load t8c
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Move result to rax
    popq %rbx
    movq %rax, 16(%rbx)  # Store element at index 2
    movq %rbx, %rax  # Array pointer result
    movq %rax, %r8  # Collection pointer
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -496(%rbp)  # Initialize toks8
    # Variable: log_op at -504(%rbp)

    # Arithmetic expression
    # Array index access: toks8
    movq -496(%rbp), %rbx  # Load array pointer from stack
    movq 8(%rbx), %rax  # Get element at index 1
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -504(%rbp)  # Initialize log_op
    # Variable: log_type at -512(%rbp)

    # Arithmetic expression
    # Array index access: log_op
    movq -504(%rbp), %rbx  # Load array pointer from stack
    movq 0(%rbx), %rax  # Get element at index 0
    movq %rax, %r8  # Array element value
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, -512(%rbp)  # Initialize log_type

    # If statement

    # Comparison with logical chaining
    movq -512(%rbp), %r8  # Load log_type
    movq $29, %r9  # Literal
    cmpq %r9, %r8
    movq $0, %rax
    sete %al
    # Single comparison result in rax
    test %rax, %rax
    jz .if_end_65
    # Then body
    .section .rodata
str_24:
    .asciz "  AST: VAR(a) and VAR(b)\n"  # string with newline
    .set str_24_len, . - str_24 - 2  # length without null and newline

    .text
    # Print:   AST: VAR(a) and VAR(b)
    movq $1, %rax              # sys_write
    movq $1, %rdi              # stdout
    leaq str_24(%rip), %rsi   # string address (RIP-relative)
    movq $str_24_len, %rdx     # string length
    addq $1, %rdx              # include newline
    syscall


    # Arithmetic expression
    # println() call
    .section .rodata
    _str_49: .asciz ""
    .section .text
    leaq _str_49(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)
.if_end_65:

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_50: .asciz ""
    .section .text
    leaq _str_50(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_51: .asciz "=== All tests completed! ==="
    .section .text
    leaq _str_51(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_52: .asciz ""
    .section .text
    leaq _str_52(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_53: .asciz "✅ Expression Parser functionality demonstrated"
    .section .text
    leaq _str_53(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_54: .asciz "✅ Operator precedence working"
    .section .text
    leaq _str_54(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    # println() call
    .section .rodata
    _str_55: .asciz "✅ All expression types supported"
    .section .text
    leaq _str_55(%rip), %r8  # Load string pointer
    movq %r8, %rdi
    call puts  # Print string + newline
    # Result in r8 (integer) or xmm0 (float)

    # Arithmetic expression
    movq $0, %r8  # Literal
    # Result in r8 (integer) or xmm0 (float)
    movq %r8, %rax  # Return value
    jmp .Lmain_return

.Lmain_return:
    movq %rbp, %rsp
    popq %rbp
    ret
